(** Blorp-owned prepared dict templates for the C backend.

    The template manifest is generated by
    [compiler/blorp/codegen_prepared_dict_renderer.brp]. OCaml still owns Core
    traversal, child expression emission, ownership analysis, ABI strings, and
    fresh temp seeds; Blorp owns the C snippet shape and temp names for prepared
    dict templates. *)

open Core_emit_context

let manifest =
  Core_emit_blorp_template.create ~label:"codegen prepared dict"
    Core_emit_blorp_prepared_dict_templates.tsv

let render_arg = Core_emit_blorp_template.render_arg
let render_template = Core_emit_blorp_template.render_exn manifest
let emit_template = Core_emit_blorp_template.emit manifest

type key_release_policy = KeepKey | ReleaseKey

let render_call_no_args function_name =
  render_template "dict_call_no_args" [ function_name ]

let render_call_with_capacity ~emit_expr ctx function_name capacity =
  let capacity_arg = render_arg ~emit_expr ctx capacity in
  render_template "dict_call_with_capacity" [ function_name; capacity_arg ]

let render_custom_ctor function_name ~hash_fn ~equals_fn ~key_release =
  render_template "dict_custom_ctor"
    [ function_name; hash_fn; equals_fn; key_release ]

let render_custom_with_capacity_ctor ~emit_expr ctx function_name capacity
    ~hash_fn ~equals_fn ~key_release =
  let capacity_arg = render_arg ~emit_expr ctx capacity in
  render_template "dict_custom_with_capacity_ctor"
    [ function_name; capacity_arg; hash_fn; equals_fn; key_release ]

let render_value_release_init temp_seed =
  render_template "dict_value_release_init" [ temp_seed ]

let render_insert temp_seed ~key_arg ~value_arg =
  render_template "dict_insert" [ temp_seed; key_arg; value_arg ]

let render_iter_pair_binding ~entry ~dict ~slot =
  render_template "dict_iter_pair_binding" [ entry; dict; slot ]

let render_iter_source_binding ~dict ~source =
  render_template "dict_iter_source_binding" [ dict; source ]

let render_iter_loop_open ~index ~dict =
  render_template "dict_iter_loop_open" [ index; dict ]

let render_iter_slot_binding ~slot ~dict ~index =
  render_template "dict_iter_slot_binding" [ slot; dict; index ]

let render_iter_deleted_slot_guard ~slot =
  render_template "dict_iter_deleted_slot_guard" [ slot ]

let render_iter_key_binding ~key_c_type ~binding ~dict ~slot =
  render_template "dict_iter_key_binding" [ key_c_type; binding; dict; slot ]

let emit_iter_source_binding ~emit_expr ctx ~dict source =
  let source_arg = render_arg ~emit_expr ctx source in
  emit_line ctx (render_iter_source_binding ~dict ~source:source_arg)

let emit_iter_loop_open ctx ~index ~dict =
  emit_line ctx (render_iter_loop_open ~index ~dict)

let emit_iter_slot_binding ctx ~slot ~dict ~index =
  emit_line ctx (render_iter_slot_binding ~slot ~dict ~index)

let emit_iter_deleted_slot_guard ctx ~slot =
  emit_line ctx (render_iter_deleted_slot_guard ~slot)

let emit_iter_key_binding ctx ~key_c_type ~binding ~dict ~slot =
  emit_line ctx (render_iter_key_binding ~key_c_type ~binding ~dict ~slot)

let emit_iter_pair_binding ctx ~entry ~dict ~slot =
  emit_line ctx (render_iter_pair_binding ~entry ~dict ~slot)

let emit_construct_result ctx ~ctor_arg ~value_needs_release =
  if value_needs_release then
    let temp_seed = string_of_int (fresh_temp ctx) in
    let release_init = render_value_release_init temp_seed in
    emit_template ctx "dict_construct_with_body"
      [ ctor_arg; temp_seed; release_init; "" ]
  else emit_template ctx "dict_construct_empty" [ ctor_arg ]

let emit_construct ~emit_key ~emit_value ctx ~ctor_arg ~value_needs_release
    ~force_wrapper entries =
  if entries = [] && (not value_needs_release) && not force_wrapper then
    emit_template ctx "dict_construct_empty" [ ctor_arg ]
  else
    let temp_seed = string_of_int (fresh_temp ctx) in
    let release_init =
      if value_needs_release then render_value_release_init temp_seed else ""
    in
    let insert_statements =
      entries
      |> List.map (fun (key, value) ->
          let key_arg = render_arg ~emit_expr:emit_key ctx key in
          let value_arg = render_arg ~emit_expr:emit_value ctx value in
          render_insert temp_seed ~key_arg ~value_arg)
      |> String.concat ""
    in
    emit_template ctx "dict_construct_with_body"
      [ ctor_arg; temp_seed; release_init; insert_statements ]

let stack_option_template_name payload_storage key_release_policy =
  match (payload_storage, key_release_policy) with
  | Core_layout_type.GeneratedStackOptionValueRecord _, KeepKey ->
      "dict_stack_option_get_value_record"
  | Core_layout_type.GeneratedStackOptionValueRecord _, ReleaseKey ->
      "dict_stack_option_get_value_record_release_key"
  | Core_layout_type.GeneratedStackOptionLong, KeepKey ->
      "dict_stack_option_get_long"
  | Core_layout_type.GeneratedStackOptionLong, ReleaseKey ->
      "dict_stack_option_get_long_release_key"
  | Core_layout_type.GeneratedStackOptionInt128, KeepKey ->
      "dict_stack_option_get_int128"
  | Core_layout_type.GeneratedStackOptionInt128, ReleaseKey ->
      "dict_stack_option_get_int128_release_key"
  | Core_layout_type.GeneratedStackOptionUInt128, KeepKey ->
      "dict_stack_option_get_uint128"
  | Core_layout_type.GeneratedStackOptionUInt128, ReleaseKey ->
      "dict_stack_option_get_uint128_release_key"

let emit_stack_option_get ~emit_expr ~emit_boxed ctx
    (abi : Core_layout_type.generated_stack_option_get_abi) dict key
    ~key_release_policy =
  let dict_arg = render_arg ~emit_expr ctx dict in
  let key_arg = render_arg ~emit_expr:emit_boxed ctx key in
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let template_name =
    stack_option_template_name abi.gsog_payload_storage key_release_policy
  in
  match abi.gsog_payload_storage with
  | Core_layout_type.GeneratedStackOptionValueRecord payload_c_type ->
      emit_template ctx template_name
        [
          dict_arg;
          key_arg;
          temp_seed;
          abi.gsog_option_c_type;
          payload_c_type;
          abi.gsog_none_value;
        ]
  | Core_layout_type.GeneratedStackOptionLong
  | Core_layout_type.GeneratedStackOptionInt128
  | Core_layout_type.GeneratedStackOptionUInt128 ->
      emit_template ctx template_name
        [
          dict_arg;
          key_arg;
          temp_seed;
          abi.gsog_option_c_type;
          abi.gsog_none_value;
        ]
