(** Blorp-owned prepared list templates for the C backend.

    The template manifest is generated by
    [compiler/blorp/codegen_prepared_list_renderer.brp]. OCaml still owns Core
    traversal, child expression emission, layout metadata, and fresh temp seeds;
    Blorp owns the C snippet shape and temp names for prepared list templates. *)

open Core
open Core_emit_context

let manifest =
  Core_emit_blorp_template.create ~label:"codegen prepared list"
    Core_emit_blorp_prepared_list_templates.tsv

let render_arg = Core_emit_blorp_template.render_arg
let render_template = Core_emit_blorp_template.render_exn manifest
let emit_template = Core_emit_blorp_template.emit manifest

type store_runtime_template =
  | SetRawStoreTemplate
  | HandoffSetOwnedStoreTemplate

type store_runtime = ListSetRaw | ListHandoffSetOwned
type alloc_template = PointerAllocTemplate | InlineAllocTemplate of string

let store_template_of_runtime = function
  | ListSetRaw -> SetRawStoreTemplate
  | ListHandoffSetOwned -> HandoffSetOwnedStoreTemplate

let pointer_store_template_name = function
  | SetRawStoreTemplate -> "list_pointer_set_raw_store"
  | HandoffSetOwnedStoreTemplate -> "list_pointer_handoff_set_owned_store"

let inline_struct_store_template_name template ~stack_result =
  match (template, stack_result) with
  | SetRawStoreTemplate, false -> "list_inline_struct_set_raw_store"
  | SetRawStoreTemplate, true -> "list_inline_struct_set_raw_store_stack_result"
  | HandoffSetOwnedStoreTemplate, false ->
      "list_inline_struct_handoff_set_owned_store"
  | HandoffSetOwnedStoreTemplate, true ->
      "list_inline_struct_handoff_set_owned_store_stack_result"

let alloc_template_of_layout (layout : list_storage_layout) =
  match layout.lsl_slots with
  | ListPointerStorage -> PointerAllocTemplate
  | ListInlineStorage width ->
      InlineAllocTemplate (string_of_int (inline_storage_width_bytes width))
  | ListInlineStructStorage c_ty ->
      InlineAllocTemplate (Printf.sprintf "sizeof(%s)" c_ty)

let runtime_storage_args (layout : list_storage_layout) : string * string =
  match layout.lsl_slots with
  | ListPointerStorage -> ("BLORP_LIST_STORAGE_POINTER", "sizeof(void*)")
  | ListInlineStorage width ->
      ( "BLORP_LIST_STORAGE_INLINE",
        string_of_int (inline_storage_width_bytes width) )
  | ListInlineStructStorage c_ty ->
      ("BLORP_LIST_STORAGE_INLINE", "sizeof(" ^ c_ty ^ ")")

let elem_release_arg ~loc layout =
  if
    list_storage_layout_requires_release_or_error ~phase:Core_error.Emit ~loc
      layout
  then "blorp_elem_release_fn"
  else "NULL"

let render_alloc_call layout capacity_arg =
  match alloc_template_of_layout layout with
  | PointerAllocTemplate ->
      render_template "list_alloc_pointer" [ capacity_arg ]
  | InlineAllocTemplate elem_size ->
      render_template "list_alloc_inline" [ capacity_arg; elem_size ]

let render_alloc_with_release ~alloc_expr ~result_tmp =
  render_template "list_alloc_with_release" [ alloc_expr; result_tmp ]

let render_alloc_for_layout_capacity_arg ctx layout ~loc capacity_arg =
  let alloc_expr = render_alloc_call layout capacity_arg in
  if
    list_storage_layout_requires_release_or_error ~phase:Core_error.Emit ~loc
      layout
  then
    let result_tmp = Printf.sprintf "__lst_%d" (fresh_temp ctx) in
    render_alloc_with_release ~alloc_expr ~result_tmp
  else alloc_expr

let emit_alloc_for_layout_capacity_arg ctx layout ~loc capacity_arg =
  emit ctx (render_alloc_for_layout_capacity_arg ctx layout ~loc capacity_arg)

let emit_alloc_for_layout ~emit_expr ctx layout ~loc capacity =
  let capacity_arg = render_arg ~emit_expr ctx capacity in
  emit_alloc_for_layout_capacity_arg ctx layout ~loc capacity_arg

let emit_alloc_for_type_capacity_arg ctx list_ty ~loc capacity_arg =
  let layout = Core_emit_layout.list_storage_layout_of_type ctx list_ty loc in
  emit_alloc_for_layout_capacity_arg ctx layout ~loc capacity_arg

let emit_alloc_for_type ~emit_expr ctx list_ty ~loc capacity =
  let capacity_arg = render_arg ~emit_expr ctx capacity in
  emit_alloc_for_type_capacity_arg ctx list_ty ~loc capacity_arg

let emit_runtime_get ~emit_expr ctx ~template_name list index =
  let list_arg = render_arg ~emit_expr ctx list in
  let index_arg = render_arg ~emit_expr ctx index in
  emit_template ctx template_name [ list_arg; index_arg ]

let emit_inline_get ~emit_expr ctx get width =
  let temp_seed = string_of_int (fresh_temp ctx) in
  let width_bytes = string_of_int (inline_storage_width_bytes width) in
  let template_name =
    match get.lg_bounds with
    | ListBoundsChecked -> "list_get_inline_checked"
    | ListBoundsProven -> "list_get_inline_proven"
  in
  let list_arg = render_arg ~emit_expr ctx get.lg_list in
  let index_arg = render_arg ~emit_expr ctx get.lg_index in
  emit_template ctx template_name
    [ list_arg; index_arg; temp_seed; width_bytes ]

let emit_inline_struct_dynamic_load ctx ~list_tmp ~idx_tmp ~out_tmp ~struct_ty
    ~bounds =
  let temp_seed = string_of_int (fresh_temp ctx) in
  let template_name =
    match bounds with
    | ListBoundsChecked -> "list_inline_struct_load_checked"
    | ListBoundsProven -> "list_inline_struct_load_proven"
  in
  emit_template ctx template_name
    [ list_tmp; idx_tmp; out_tmp; temp_seed; struct_ty ]

let render_inline_struct_unbox_list_name temp_seed =
  render_template "list_inline_struct_unbox_list_name" [ temp_seed ]

let render_inline_struct_unbox_index_name temp_seed =
  render_template "list_inline_struct_unbox_index_name" [ temp_seed ]

let render_inline_struct_unbox_out_name temp_seed =
  render_template "list_inline_struct_unbox_out_name" [ temp_seed ]

let emit_inline_struct_unbox_open ~emit_expr ctx ~list_tmp ~idx_tmp ~out_tmp
    ~struct_ty get =
  let list_arg = render_arg ~emit_expr ctx get.lg_list in
  let index_arg = render_arg ~emit_expr ctx get.lg_index in
  emit_template ctx "list_inline_struct_unbox_open"
    [ list_tmp; list_arg; idx_tmp; index_arg; struct_ty; out_tmp ];
  emit ctx " "

let emit_inline_struct_unbox_close ctx ~out_tmp =
  emit_template ctx "list_inline_struct_unbox_close" [ out_tmp ]

let emit_inline_struct_unbox_get ~emit_expr ctx get ~struct_ty =
  let temp_seed = string_of_int (fresh_temp ctx) in
  let list_tmp = render_inline_struct_unbox_list_name temp_seed in
  let idx_tmp = render_inline_struct_unbox_index_name temp_seed in
  let out_tmp = render_inline_struct_unbox_out_name temp_seed in
  emit_inline_struct_unbox_open ~emit_expr ctx ~list_tmp ~idx_tmp ~out_tmp
    ~struct_ty get;
  emit_inline_struct_dynamic_load ctx ~list_tmp ~idx_tmp ~out_tmp ~struct_ty
    ~bounds:get.lg_bounds;
  emit ctx " ";
  emit_inline_struct_unbox_close ctx ~out_tmp

let emit_inline_bits_load ctx ~list_tmp ~idx_tmp ~bits_tmp ~width =
  let width_bytes = string_of_int (inline_storage_width_bytes width) in
  emit_template ctx "list_inline_bits_load"
    [ list_tmp; idx_tmp; bits_tmp; width_bytes ]

let emit_inline_bits_store ~emit_expr ~emit_boxed ctx lst idx val_ width =
  let temp_seed = string_of_int (fresh_temp ctx) in
  let width_bytes = string_of_int (inline_storage_width_bytes width) in
  let list_arg = render_arg ~emit_expr ctx lst in
  let index_arg = render_arg ~emit_expr ctx idx in
  let value_arg = render_arg ~emit_expr:emit_boxed ctx val_ in
  emit_template ctx "list_inline_bits_store"
    [ list_arg; index_arg; value_arg; temp_seed; width_bytes ]

let emit_pointer_store ~emit_expr ~emit_boxed ctx ~template lst idx val_ =
  let list_arg = render_arg ~emit_expr ctx lst in
  let index_arg = render_arg ~emit_expr ctx idx in
  let value_arg = render_arg ~emit_expr:emit_boxed ctx val_ in
  let template_name = pointer_store_template_name template in
  emit_template ctx template_name [ list_arg; index_arg; value_arg ]

let emit_inline_struct_store_template ~emit_expr ctx ~template lst idx val_
    ~struct_ty =
  let temp_seed = string_of_int (fresh_temp ctx) in
  let list_arg = render_arg ~emit_expr ctx lst in
  let index_arg = render_arg ~emit_expr ctx idx in
  let value_arg = render_arg ~emit_expr ctx val_ in
  let template_name =
    inline_struct_store_template_name template
      ~stack_result:(Core_layout_type.is_stack_result_type ~reg:ctx.reg val_.ty)
  in
  emit_template ctx template_name
    [ list_arg; index_arg; value_arg; temp_seed; struct_ty ]

let emit_store ~emit_expr ~emit_boxed ctx store_runtime lst idx val_ =
  let layout =
    Core_emit_layout.list_storage_layout_of_type ctx lst.ty lst.loc
  in
  match layout.lsl_slots with
  | ListInlineStructStorage c_ty ->
      emit_inline_struct_store_template ~emit_expr ctx
        ~template:(store_template_of_runtime store_runtime)
        lst idx val_ ~struct_ty:c_ty
  | ListInlineStorage width ->
      emit_inline_bits_store ~emit_expr ~emit_boxed ctx lst idx val_ width
  | ListPointerStorage ->
      emit_pointer_store ~emit_expr ~emit_boxed ctx
        ~template:(store_template_of_runtime store_runtime)
        lst idx val_

let swap_prefix_args ~emit_expr ctx lst left_index right_index =
  let temp_seed = string_of_int (fresh_temp ctx) in
  let list_arg = render_arg ~emit_expr ctx lst in
  let left_index_arg = render_arg ~emit_expr ctx left_index in
  let right_index_arg = render_arg ~emit_expr ctx right_index in
  (list_arg, left_index_arg, right_index_arg, temp_seed)

let emit_pointer_swap ~emit_expr ctx lst left_index right_index =
  let list_arg, left_index_arg, right_index_arg, temp_seed =
    swap_prefix_args ~emit_expr ctx lst left_index right_index
  in
  emit_template ctx "list_pointer_swap"
    [ list_arg; left_index_arg; right_index_arg; temp_seed ]

let emit_inline_bits_swap ~emit_expr ctx lst left_index right_index width =
  let list_arg, left_index_arg, right_index_arg, temp_seed =
    swap_prefix_args ~emit_expr ctx lst left_index right_index
  in
  let width_bytes = string_of_int (inline_storage_width_bytes width) in
  emit_template ctx "list_inline_bits_swap"
    [ list_arg; left_index_arg; right_index_arg; temp_seed; width_bytes ]

let emit_inline_struct_swap ~emit_expr ctx lst left_index right_index =
  let list_arg, left_index_arg, right_index_arg, temp_seed =
    swap_prefix_args ~emit_expr ctx lst left_index right_index
  in
  emit_template ctx "list_inline_struct_swap"
    [ list_arg; left_index_arg; right_index_arg; temp_seed ]

let emit_swap_slots ~emit_expr ctx lst left_index right_index =
  let layout =
    Core_emit_layout.list_storage_layout_of_type ctx lst.ty lst.loc
  in
  match layout.lsl_slots with
  | ListInlineStructStorage _ ->
      emit_inline_struct_swap ~emit_expr ctx lst left_index right_index
  | ListInlineStorage width ->
      emit_inline_bits_swap ~emit_expr ctx lst left_index right_index width
  | ListPointerStorage ->
      emit_pointer_swap ~emit_expr ctx lst left_index right_index

let emit_handoff_set_source_slot ~emit_expr ctx result out_idx source source_idx
    =
  let result_arg = render_arg ~emit_expr ctx result in
  let out_idx_arg = render_arg ~emit_expr ctx out_idx in
  let source_arg = render_arg ~emit_expr ctx source in
  let source_idx_arg = render_arg ~emit_expr ctx source_idx in
  emit_template ctx "list_handoff_set_source_slot"
    [ result_arg; out_idx_arg; source_arg; source_idx_arg ]

let emit_copy_span_uninit ~emit_expr ctx dst dst_start src src_start count =
  let dst_arg = render_arg ~emit_expr ctx dst in
  let dst_start_arg = render_arg ~emit_expr ctx dst_start in
  let src_arg = render_arg ~emit_expr ctx src in
  let src_start_arg = render_arg ~emit_expr ctx src_start in
  let count_arg = render_arg ~emit_expr ctx count in
  emit_template ctx "list_copy_span_uninit"
    [ dst_arg; dst_start_arg; src_arg; src_start_arg; count_arg ]

let emit_ensure_unique ~emit_expr ctx lst =
  let temp_seed = string_of_int (fresh_temp ctx) in
  let list_arg = render_arg ~emit_expr ctx lst in
  emit_template ctx "list_ensure_unique" [ list_arg; temp_seed ]

let emit_ensure_capacity ~emit_expr ctx lst cap =
  let temp_seed = string_of_int (fresh_temp ctx) in
  let list_arg = render_arg ~emit_expr ctx lst in
  let cap_arg = render_arg ~emit_expr ctx cap in
  emit_template ctx "list_ensure_capacity" [ list_arg; cap_arg; temp_seed ]

let emit_reuse_alloc ~emit_expr ctx lst cap =
  let list_arg = render_arg ~emit_expr ctx lst in
  let cap_arg = render_arg ~emit_expr ctx cap in
  emit_template ctx "list_reuse_alloc" [ list_arg; cap_arg ]

let emit_reuse_alloc_with_release ~emit_expr ctx lst cap =
  let temp_seed = string_of_int (fresh_temp ctx) in
  let list_arg = render_arg ~emit_expr ctx lst in
  let cap_arg = render_arg ~emit_expr ctx cap in
  emit_template ctx "list_reuse_alloc_with_release"
    [ list_arg; cap_arg; temp_seed ]

let emit_reuse_alloc_for_result ~emit_expr ctx result lst cap =
  let layout =
    Core_emit_layout.list_storage_layout_of_type ctx result.ty result.loc
  in
  if
    list_storage_layout_requires_release_or_error ~phase:Core_error.Emit
      ~loc:result.loc layout
  then emit_reuse_alloc_with_release ~emit_expr ctx lst cap
  else emit_reuse_alloc ~emit_expr ctx lst cap

let emit_retain_for ~emit_expr ~emit_boxed ctx lst value =
  let list_arg = render_arg ~emit_expr ctx lst in
  let value_arg = render_arg ~emit_expr:emit_boxed ctx value in
  emit_template ctx "list_retain_for" [ list_arg; value_arg ]

let emit_retain_for_noop ctx = emit_template ctx "list_retain_for_noop" []

let emit_retain_for_storage ~emit_expr ~emit_boxed ctx lst value =
  let layout =
    Core_emit_layout.list_storage_layout_of_type ctx lst.ty lst.loc
  in
  if
    list_storage_layout_requires_retain_or_error ~phase:Core_error.Emit
      ~loc:lst.loc layout
  then emit_retain_for ~emit_expr ~emit_boxed ctx lst value
  else emit_retain_for_noop ctx

let render_construct_init_elem_release ~list_tmp =
  render_template "list_construct_init_elem_release" [ list_tmp ]

let render_construct_name temp_seed =
  render_template "list_construct_name" [ temp_seed ]

let render_construct ~list_tmp ~alloc_call ~statements =
  render_template "list_construct"
    [ list_tmp; alloc_call; String.concat " " statements ]

let emit_construct ctx ~list_tmp ~alloc_call ~statements =
  emit ctx (render_construct ~list_tmp ~alloc_call ~statements)

let render_construct_inline_struct_set ~emit_expr ctx ~list_tmp ~index
    ~struct_ty value =
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let value_arg = render_arg ~emit_expr ctx value in
  render_template "list_construct_inline_struct_set"
    [ list_tmp; string_of_int index; value_arg; temp_seed; struct_ty ]

let render_construct_set_len ~list_tmp ~len =
  render_template "list_construct_set_len" [ list_tmp; string_of_int len ]

let render_construct_append ~emit_boxed ctx ~list_tmp ~owned value =
  let value_arg = render_arg ~emit_expr:emit_boxed ctx value in
  let template_name =
    if owned then "list_construct_append_owned" else "list_construct_append"
  in
  render_template template_name [ list_tmp; value_arg ]

let render_handoff_capacity_name temp_seed =
  render_template "list_handoff_capacity_name" [ temp_seed ]

let render_handoff_reuse_name temp_seed =
  render_template "list_handoff_reuse_name" [ temp_seed ]

let render_handoff_release_name temp_seed =
  render_template "list_handoff_release_name" [ temp_seed ]

let emit_handoff_open ~emit_expr ctx ~source_ty_c ~source_c source ~capacity_c
    capacity ~length_c ~release_c ~release_fn_c =
  let source_arg = render_arg ~emit_expr ctx source in
  let capacity_arg = render_arg ~emit_expr ctx capacity in
  emit_template ctx "list_handoff_open"
    [
      source_ty_c;
      source_c;
      source_arg;
      capacity_c;
      capacity_arg;
      length_c;
      release_c;
      release_fn_c;
    ];
  emit ctx " "

let emit_handoff_begin_borrow ctx ~result_ty_c ~result_c ~capacity_c ~release_c
    ~storage_mode_c ~elem_size_c ~out_c =
  emit_template ctx "list_handoff_begin_borrow"
    [
      result_ty_c;
      result_c;
      capacity_c;
      release_c;
      storage_mode_c;
      elem_size_c;
      out_c;
    ];
  emit ctx " "

let emit_handoff_begin_reuse ctx ~result_ty_c ~result_c ~source_c ~capacity_c
    ~release_c ~storage_mode_c ~elem_size_c ~reuse_c ~out_c =
  emit_template ctx "list_handoff_begin_reuse"
    [
      result_ty_c;
      result_c;
      source_c;
      capacity_c;
      release_c;
      storage_mode_c;
      elem_size_c;
      reuse_c;
      out_c;
    ];
  emit ctx " "

let emit_handoff_finish_borrow ctx ~result_c ~out_c ~length_c =
  emit_template ctx "list_handoff_finish_borrow" [ result_c; out_c; length_c ];
  emit ctx " "

let emit_handoff_finish_reuse ctx ~result_c ~out_c ~length_c ~reuse_c ~source_c
    =
  emit_template ctx "list_handoff_finish_reuse"
    [ result_c; out_c; length_c; reuse_c; source_c ];
  emit ctx " "

let emit_handoff_close ctx ~result_c =
  emit_template ctx "list_handoff_close" [ result_c ]

let render_construct_statements ~emit_expr ~emit_boxed ctx layout ~list_tmp
    ~elem_needs_release elems =
  match layout.lsl_slots with
  | ListInlineStructStorage c_ty ->
      let writes =
        List.mapi
          (fun i value ->
            render_construct_inline_struct_set ~emit_expr ctx ~list_tmp ~index:i
              ~struct_ty:c_ty value.bsv_box.box_value)
          elems
      in
      writes @ [ render_construct_set_len ~list_tmp ~len:(List.length elems) ]
  | ListPointerStorage | ListInlineStorage _ ->
      let init =
        if elem_needs_release then
          [ render_construct_init_elem_release ~list_tmp ]
        else []
      in
      let appends =
        List.map
          (fun value ->
            render_construct_append ~emit_boxed ctx ~list_tmp
              ~owned:(elem_needs_release && value.bsv_transfers_ownership)
              value)
          elems
      in
      init @ appends

let emit_get ~emit_expr (ctx : Core_emit_context.t) (get : list_get) : unit =
  match get.lg_layout.lsl_slots with
  | ListPointerStorage ->
      emit_runtime_get ~emit_expr ctx ~template_name:"list_get_pointer"
        get.lg_list get.lg_index
  | ListInlineStorage width -> emit_inline_get ~emit_expr ctx get width
  | ListInlineStructStorage _ ->
      emit_runtime_get ~emit_expr ctx ~template_name:"list_get_pointer"
        get.lg_list get.lg_index
