(** Blorp-owned prepared string templates for the C backend.

    The template manifest is generated by
    [compiler/blorp/codegen_prepared_string_renderer.brp]. OCaml still owns Core
    traversal, child expression emission, and fresh temp seeds; Blorp owns the C
    snippet shape, including local temp-name conventions. *)

open Core
open Core_emit_context

let manifest =
  Core_emit_blorp_template.create ~label:"codegen prepared string"
    Core_emit_blorp_prepared_string_templates.tsv

let render_arg = Core_emit_blorp_template.render_arg
let emit_template = Core_emit_blorp_template.emit manifest

let emit_find_byte_from ~emit_expr (ctx : Core_emit_context.t) source byte start
    : unit =
  let temp_seed = string_of_int (fresh_temp ctx) in
  let source_arg = render_arg ~emit_expr ctx source in
  let byte_arg = render_arg ~emit_expr ctx byte in
  let start_arg = render_arg ~emit_expr ctx start in
  emit_template ctx "string_find_byte_from"
    [ source_arg; byte_arg; start_arg; temp_seed ]

let emit_byte_read ~emit_expr (ctx : Core_emit_context.t)
    (read : string_byte_read) : unit =
  let source_arg = render_arg ~emit_expr ctx read.sbr_source in
  let index_arg = render_arg ~emit_expr ctx read.sbr_index in
  emit_template ctx "string_byte_read" [ source_arg; index_arg ]

let emit_byte_write ~emit_expr (ctx : Core_emit_context.t)
    (write : string_byte_write) : unit =
  let target_arg = render_arg ~emit_expr ctx write.sbw_target in
  let index_arg = render_arg ~emit_expr ctx write.sbw_index in
  let byte_arg = render_arg ~emit_expr ctx write.sbw_byte in
  emit_template ctx "string_byte_write" [ target_arg; index_arg; byte_arg ]

let emit_byte_copy_intrinsic ~emit_expr (ctx : Core_emit_context.t) dst dst_pos
    src src_pos len : unit =
  let temp_seed = string_of_int (fresh_temp ctx) in
  let dst_arg = render_arg ~emit_expr ctx dst in
  let dst_pos_arg = render_arg ~emit_expr ctx dst_pos in
  let src_arg = render_arg ~emit_expr ctx src in
  let src_pos_arg = render_arg ~emit_expr ctx src_pos in
  let len_arg = render_arg ~emit_expr ctx len in
  emit_template ctx "string_byte_copy"
    [ dst_arg; dst_pos_arg; src_arg; src_pos_arg; len_arg; temp_seed ]

let emit_byte_copy ~emit_expr (ctx : Core_emit_context.t)
    (copy : string_byte_copy) : unit =
  emit_byte_copy_intrinsic ~emit_expr ctx copy.sbc_dst copy.sbc_dst_pos
    copy.sbc_src copy.sbc_src_pos copy.sbc_len

let emit_set_len_intrinsic ~emit_expr (ctx : Core_emit_context.t) target len :
    unit =
  let target_arg = render_arg ~emit_expr ctx target in
  let len_arg = render_arg ~emit_expr ctx len in
  emit_template ctx "string_set_len" [ target_arg; len_arg ]

let emit_set_len ~emit_expr (ctx : Core_emit_context.t)
    (set_len : string_set_len) : unit =
  emit_set_len_intrinsic ~emit_expr ctx set_len.ssl_target set_len.ssl_len
