(** Blorp-owned tuple templates for the C backend.

    The template manifest is generated by
    [compiler/blorp/codegen_prepared_tuple_renderer.brp]. OCaml still owns Core
    traversal, child expression emission, release-mask analysis, and fresh temp
    seeds; Blorp owns tuple construction and field-access C shapes plus tuple
    temp names. *)

open Core

let manifest =
  Core_emit_blorp_template.create ~label:"codegen prepared tuple"
    Core_emit_blorp_prepared_tuple_templates.tsv

let render_arg = Core_emit_blorp_template.render_arg
let render_template = Core_emit_blorp_template.render_exn manifest
let emit_template = Core_emit_blorp_template.emit manifest
let render_tuple_name temp_seed = render_template "tuple_name" [ temp_seed ]
let render_tuple_arg value_arg = render_template "tuple_arg" [ value_arg ]

let render_tuple_args ~emit_boxed ctx elems =
  elems
  |> List.map (fun value ->
      render_tuple_arg (render_arg ~emit_expr:emit_boxed ctx value))
  |> String.concat ""

let emit_tuple_construct ctx ~arity ~args =
  emit_template ctx "tuple_construct" [ arity; args ]

let render_tuple_retain_elem ~tuple_tmp ~index =
  render_template "tuple_retain_elem" [ tuple_tmp; string_of_int index ]

let render_tuple_retain_statements ~tuple_tmp ~retain_mask elems =
  elems
  |> List.mapi (fun i _ ->
      if retain_mask land (1 lsl i) <> 0 then
        Some (render_tuple_retain_elem ~tuple_tmp ~index:i)
      else None)
  |> List.filter_map Fun.id |> String.concat " "

let render_tuple_construct_with_rc ~tuple_tmp ~arity ~args ~retain_statements
    ~release_mask =
  render_template "tuple_construct_with_rc"
    [ tuple_tmp; arity; args; retain_statements; string_of_int release_mask ]

let emit_tuple_construct_with_rc ctx ~tuple_tmp ~arity ~args ~retain_statements
    ~release_mask =
  Core_emit_context.emit ctx
    (render_tuple_construct_with_rc ~tuple_tmp ~arity ~args ~retain_statements
       ~release_mask)

let render_tuple_field_element ~tuple_tmp ~field =
  render_template "tuple_field_element" [ tuple_tmp; field ]

let render_tuple_field_element_at ~tuple_tmp ~index =
  render_tuple_field_element ~tuple_tmp ~field:(string_of_int index)

let render_tuple_field_access ~tuple_tmp ~source ~read =
  render_template "tuple_field_access" [ tuple_tmp; source; read ]

let emit_field_access ~emit_expr ~render_read ctx obj field =
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let tuple_tmp = render_tuple_name temp_seed in
  let source = render_arg ~emit_expr ctx obj in
  let element = render_tuple_field_element ~tuple_tmp ~field in
  let read = render_read element in
  Core_emit_context.emit ctx
    (render_tuple_field_access ~tuple_tmp ~source ~read)

let emit_construct ~emit_boxed ctx tc =
  let arity = string_of_int (List.length tc.tc_elems) in
  let args = render_tuple_args ~emit_boxed ctx tc.tc_elems in
  if tc.tc_release_mask = 0 then emit_tuple_construct ctx ~arity ~args
  else
    let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
    let tuple_tmp = render_tuple_name temp_seed in
    let retain_statements =
      render_tuple_retain_statements ~tuple_tmp ~retain_mask:tc.tc_retain_mask
        tc.tc_elems
    in
    emit_tuple_construct_with_rc ctx ~tuple_tmp ~arity ~args ~retain_statements
      ~release_mask:tc.tc_release_mask
