(** Blorp-owned prepared tensor templates for the C backend.

    The template manifest is generated by
    [compiler/blorp/codegen_prepared_tensor_renderer.brp]. OCaml still owns
    Core traversal, child expression emission, ABI strings, fresh temp seeds,
    and variable-name escaping; Blorp owns local temp-name conventions inside
    prepared tensor Core node templates. *)

open Core

let manifest =
  Core_emit_blorp_template.create ~label:"codegen prepared tensor"
    Core_emit_blorp_prepared_tensor_templates.tsv

let render_arg = Core_emit_blorp_template.render_arg
let render_template = Core_emit_blorp_template.render_exn manifest
let emit_template = Core_emit_blorp_template.emit manifest
let tensor_view_c_name v = Codegen_types.escape_c_ident (Var.to_c_name v)

type fill_value_policy = KeepFillValue | ReleaseFillValue

type storage_check_template =
  | WordStorageCheckTemplate
  | F64StorageCheckTemplate
  | F32StorageCheckTemplate
  | I64StorageCheckTemplate

type raw_scalar_get_template = F64RawGetTemplate | F32RawGetTemplate

type literal_write_template =
  | LiteralF32WriteTemplate
  | LiteralF64WriteTemplate
  | LiteralI64WriteTemplate
  | LiteralWordWriteTemplate
  | LiteralPackedWriteTemplate

type alloc_template =
  | PointerAllocTemplate
  | I64AllocTemplate
  | F64AllocTemplate
  | F32AllocTemplate
  | PackedAllocTemplate of int
  | SizedAllocTemplate of string

type ranked_alloc_template =
  | PointerRankedAllocTemplate
  | I64RankedAllocTemplate
  | F64RankedAllocTemplate
  | F32RankedAllocTemplate
  | PackedRankedAllocTemplate of int
  | SizedRankedAllocTemplate of string

let storage_check_template_name = function
  | WordStorageCheckTemplate -> "tensor_is_word_storage"
  | F64StorageCheckTemplate -> "tensor_is_f64_storage"
  | F32StorageCheckTemplate -> "tensor_is_f32_storage"
  | I64StorageCheckTemplate -> "tensor_is_i64_storage"

let raw_scalar_get_template_name = function
  | F64RawGetTemplate -> "tensor_get_f64_raw_unchecked"
  | F32RawGetTemplate -> "tensor_get_f32_raw_unchecked"

let literal_write_template_name = function
  | LiteralF32WriteTemplate -> "tensor_literal_write_f32"
  | LiteralF64WriteTemplate -> "tensor_literal_write_f64"
  | LiteralI64WriteTemplate -> "tensor_literal_write_i64"
  | LiteralWordWriteTemplate -> "tensor_literal_write_word"
  | LiteralPackedWriteTemplate -> "tensor_literal_write_packed"

let alloc_template_of_layout (layout : tensor_storage_layout) =
  match layout.tsl_slots with
  | TensorRawScalarStorage TensorInt64Elements -> I64AllocTemplate
  | TensorRawScalarStorage TensorFloat64Elements -> F64AllocTemplate
  | TensorRawScalarStorage TensorFloat32Elements -> F32AllocTemplate
  | TensorPackedStorage width ->
      PackedAllocTemplate (Core.inline_storage_width_bytes width)
  | TensorInlineStructStorage c_ty -> SizedAllocTemplate c_ty
  | TensorWordStorage | TensorBoxedStorage -> PointerAllocTemplate

let runtime_storage_args (layout : tensor_storage_layout) : string * string =
  match layout.tsl_slots with
  | TensorRawScalarStorage TensorFloat64Elements ->
      ("BLORP_VECTOR_STORAGE_F64", "sizeof(double)")
  | TensorRawScalarStorage TensorFloat32Elements ->
      ("BLORP_VECTOR_STORAGE_F32", "sizeof(float)")
  | TensorRawScalarStorage TensorInt64Elements ->
      ("BLORP_VECTOR_STORAGE_I64", "sizeof(long)")
  | TensorInlineStructStorage c_ty ->
      ("BLORP_VECTOR_STORAGE_INLINE", "sizeof(" ^ c_ty ^ ")")
  | TensorPackedStorage _ | TensorWordStorage | TensorBoxedStorage ->
      ("BLORP_VECTOR_STORAGE_POINTER", "sizeof(void*)")

let callback_result_encoding_arg (layout : tensor_storage_layout) : string =
  match layout.tsl_slots with
  | TensorInlineStructStorage _ -> "BLORP_VECTOR_CALLBACK_BOXED_STRUCT"
  | TensorRawScalarStorage TensorFloat64Elements ->
      "BLORP_VECTOR_CALLBACK_BOXED_FLOAT"
  | TensorRawScalarStorage TensorFloat32Elements ->
      "BLORP_VECTOR_CALLBACK_BOXED_FLOAT32"
  | TensorRawScalarStorage TensorInt64Elements
  | TensorPackedStorage _ | TensorWordStorage | TensorBoxedStorage ->
      "BLORP_VECTOR_CALLBACK_BITS"

let render_alloc_template template size_arg =
  match template with
  | PointerAllocTemplate -> render_template "tensor_alloc_pointer" [ size_arg ]
  | I64AllocTemplate -> render_template "tensor_alloc_i64" [ size_arg ]
  | F64AllocTemplate -> render_template "tensor_alloc_f64" [ size_arg ]
  | F32AllocTemplate -> render_template "tensor_alloc_f32" [ size_arg ]
  | PackedAllocTemplate elem_size ->
      render_template "tensor_alloc_packed"
        [ size_arg; string_of_int elem_size ]
  | SizedAllocTemplate struct_ty ->
      render_template "tensor_alloc_sized" [ size_arg; struct_ty ]

let ranked_alloc_template_of_layout (layout : tensor_storage_layout) =
  match layout.tsl_slots with
  | TensorRawScalarStorage TensorInt64Elements -> I64RankedAllocTemplate
  | TensorRawScalarStorage TensorFloat64Elements -> F64RankedAllocTemplate
  | TensorRawScalarStorage TensorFloat32Elements -> F32RankedAllocTemplate
  | TensorPackedStorage width ->
      PackedRankedAllocTemplate (Core.inline_storage_width_bytes width)
  | TensorInlineStructStorage c_ty -> SizedRankedAllocTemplate c_ty
  | TensorWordStorage | TensorBoxedStorage -> PointerRankedAllocTemplate

let render_ranked_alloc_template template ~first_dim ~total_dim =
  match template with
  | PointerRankedAllocTemplate ->
      render_template "tensor_ranked_alloc_pointer" [ first_dim; total_dim ]
  | I64RankedAllocTemplate ->
      render_template "tensor_ranked_alloc_i64" [ first_dim; total_dim ]
  | F64RankedAllocTemplate ->
      render_template "tensor_ranked_alloc_f64" [ first_dim; total_dim ]
  | F32RankedAllocTemplate ->
      render_template "tensor_ranked_alloc_f32" [ first_dim; total_dim ]
  | PackedRankedAllocTemplate elem_size ->
      render_template "tensor_ranked_alloc_packed"
        [ first_dim; total_dim; string_of_int elem_size ]
  | SizedRankedAllocTemplate struct_ty ->
      render_template "tensor_ranked_alloc_sized"
        [ first_dim; total_dim; struct_ty ]

let render_ranked_alloc_call layout ~first_dim ~total_dim =
  render_ranked_alloc_template
    (ranked_alloc_template_of_layout layout)
    ~first_dim ~total_dim

let render_fill_alloc_call layout ~first_dim ~total_dim loc =
  match ranked_alloc_template_of_layout layout with
  | I64RankedAllocTemplate ->
      render_ranked_alloc_template I64RankedAllocTemplate ~first_dim ~total_dim
  | F64RankedAllocTemplate ->
      render_ranked_alloc_template F64RankedAllocTemplate ~first_dim ~total_dim
  | F32RankedAllocTemplate ->
      render_ranked_alloc_template F32RankedAllocTemplate ~first_dim ~total_dim
  | PackedRankedAllocTemplate elem_size ->
      render_ranked_alloc_template (PackedRankedAllocTemplate elem_size)
        ~first_dim ~total_dim
  | PointerRankedAllocTemplate | SizedRankedAllocTemplate _ ->
      Core_error.errorf Core_error.Emit loc
        "unsupported tensor fill allocation layout"

let render_literal_alloc_call layout shape =
  match shape with
  | TensorStaticShape (first :: _ as dims) ->
      let total = List.fold_left ( * ) 1 dims in
      render_ranked_alloc_call layout ~first_dim:(string_of_int first)
        ~total_dim:(string_of_int total)
  | TensorStaticShape [] ->
      render_alloc_template (alloc_template_of_layout layout) "0"
  | TensorVectorLength n ->
      render_alloc_template (alloc_template_of_layout layout) (string_of_int n)

let render_literal_name temp_seed =
  render_template "tensor_literal_name" [ temp_seed ]

let render_literal_construct ~tensor_tmp ~alloc_call ~statements =
  render_template "tensor_literal_construct"
    [ tensor_tmp; alloc_call; String.concat " " statements ]

let emit_literal_construct ctx ~tensor_tmp ~alloc_call ~statements =
  Core_emit_context.emit ctx
    (render_literal_construct ~tensor_tmp ~alloc_call ~statements)

let render_literal_init_elem_release ~tensor_tmp =
  render_template "tensor_init_elem_release" [ tensor_tmp ]

let render_literal_write ~emit_expr ctx template ~tensor_tmp ~index value =
  let value_arg = render_arg ~emit_expr ctx value in
  render_template
    (literal_write_template_name template)
    [ tensor_tmp; string_of_int index; value_arg ]

let render_literal_f32_write ~emit_expr ctx ~tensor_tmp ~index value =
  render_literal_write ~emit_expr ctx LiteralF32WriteTemplate ~tensor_tmp ~index
    value

let render_literal_f64_write ~emit_expr ctx ~tensor_tmp ~index value =
  render_literal_write ~emit_expr ctx LiteralF64WriteTemplate ~tensor_tmp ~index
    value

let render_literal_i64_write ~emit_expr ctx ~tensor_tmp ~index value =
  render_literal_write ~emit_expr ctx LiteralI64WriteTemplate ~tensor_tmp ~index
    value

let render_literal_word_write ~emit_expr ctx ~tensor_tmp ~index value =
  render_literal_write ~emit_expr ctx LiteralWordWriteTemplate ~tensor_tmp
    ~index value

let render_literal_packed_write ~emit_expr ctx ~tensor_tmp ~index value =
  render_literal_write ~emit_expr ctx LiteralPackedWriteTemplate ~tensor_tmp
    ~index value

let render_literal_inline_struct_write ~emit_expr ctx ~tensor_tmp ~index
    ~struct_ty value =
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let value_arg = render_arg ~emit_expr ctx value in
  render_template "tensor_literal_write_inline_struct"
    [ tensor_tmp; string_of_int index; value_arg; temp_seed; struct_ty ]

let render_literal_boxed_write_rendered ~tensor_tmp ~index ~value_arg =
  render_template "tensor_literal_write_boxed"
    [ tensor_tmp; string_of_int index; value_arg ]

let render_literal_boxed_write ~emit_boxed ctx ~tensor_tmp ~index value =
  let value_arg = render_arg ~emit_expr:emit_boxed ctx value in
  render_literal_boxed_write_rendered ~tensor_tmp ~index ~value_arg

let render_literal_boxed_seeded_write ~emit_boxed ctx template_name ~tensor_tmp
    ~index value =
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let value_arg = render_arg ~emit_expr:emit_boxed ctx value in
  render_template template_name
    [ tensor_tmp; string_of_int index; value_arg; temp_seed ]

let render_literal_boxed_owned_write ~emit_boxed ctx ~tensor_tmp ~index value =
  render_literal_boxed_seeded_write ~emit_boxed ctx
    "tensor_literal_write_boxed_owned" ~tensor_tmp ~index value

let render_literal_boxed_borrowed_write ~emit_boxed ctx ~tensor_tmp ~index value
    =
  render_literal_boxed_seeded_write ~emit_boxed ctx
    "tensor_literal_write_boxed_borrowed" ~tensor_tmp ~index value

let render_literal_statements ~emit_expr ~emit_boxed ctx ~tensor_tmp
    ~elem_needs_release payload =
  match payload with
  | TensorRawElements (TensorFloat32Elements, elems) ->
      List.mapi
        (fun i el ->
          render_literal_f32_write ~emit_expr ctx ~tensor_tmp ~index:i el)
        elems
  | TensorRawElements (TensorFloat64Elements, elems) ->
      List.mapi
        (fun i el ->
          render_literal_f64_write ~emit_expr ctx ~tensor_tmp ~index:i el)
        elems
  | TensorRawElements (TensorInt64Elements, elems) ->
      List.mapi
        (fun i el ->
          render_literal_i64_write ~emit_expr ctx ~tensor_tmp ~index:i el)
        elems
  | TensorWordElements elems ->
      List.mapi
        (fun i el ->
          render_literal_word_write ~emit_expr ctx ~tensor_tmp ~index:i el)
        elems
  | TensorPackedElements (_width, elems) ->
      List.mapi
        (fun i el ->
          render_literal_packed_write ~emit_expr ctx ~tensor_tmp ~index:i el)
        elems
  | TensorInlineStructElements (c_ty, elems) ->
      List.mapi
        (fun i el ->
          render_literal_inline_struct_write ~emit_expr ctx ~tensor_tmp ~index:i
            ~struct_ty:c_ty el)
        elems
  | TensorBoxedElements elems ->
      List.mapi
        (fun i value ->
          if elem_needs_release then
            if value.bsv_transfers_ownership then
              render_literal_boxed_owned_write ~emit_boxed ctx ~tensor_tmp
                ~index:i value
            else
              render_literal_boxed_borrowed_write ~emit_boxed ctx ~tensor_tmp
                ~index:i value
          else
            render_literal_boxed_write ~emit_boxed ctx ~tensor_tmp ~index:i
              value)
        elems

let fill_inline_struct_value_source value =
  match value.desc with
  | CBoxTyped b -> b.box_value
  | CBox (inner, _) -> inner
  | _ -> value

let render_dim_args ~emit_expr ctx dims =
  dims
  |> List.map (fun dim -> ", " ^ render_arg ~emit_expr ctx dim)
  |> String.concat ""

let emit_fill_inline_struct ~emit_expr ctx function_name value dims ~struct_ty =
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let value_arg =
    render_arg ~emit_expr ctx (fill_inline_struct_value_source value)
  in
  let dim_args = render_dim_args ~emit_expr ctx dims in
  emit_template ctx "tensor_fill_inline_struct"
    [ function_name; value_arg; dim_args; temp_seed; struct_ty ]

let emit_fill_boxed ~emit_expr ~emit_boxed ctx function_name value dims
    ~fill_value_policy =
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let value_arg = render_arg ~emit_expr:emit_boxed ctx value in
  let dim_args = render_dim_args ~emit_expr ctx dims in
  let template_name =
    match fill_value_policy with
    | KeepFillValue -> "tensor_fill_boxed"
    | ReleaseFillValue -> "tensor_fill_boxed_release_value"
  in
  emit_template ctx template_name
    [ function_name; value_arg; dim_args; temp_seed ]

let render_fill_dim_name temp_seed index =
  render_template "tensor_fill_dim_name" [ temp_seed; string_of_int index ]

let render_fill_total_name temp_seed =
  render_template "tensor_fill_total_name" [ temp_seed ]

let render_fill_dim_bind ~emit_expr ctx temp_seed index dim =
  let dim_arg = render_arg ~emit_expr ctx dim in
  render_template "tensor_fill_dim_bind"
    [ temp_seed; string_of_int index; dim_arg ]

let render_fill_total_expr dim_tmps =
  let rec product = function
    | [] -> "0"
    | [ dim ] -> dim
    | dim :: rest -> Printf.sprintf "(%s * %s)" dim (product rest)
  in
  product dim_tmps

let emit_direct_fill_factory ~emit_expr ctx loc (layout : tensor_storage_layout)
    value dims =
  match (layout.tsl_slots, dims) with
  | (TensorRawScalarStorage _ | TensorPackedStorage _), [] ->
      Core_error.errorf Core_error.Emit loc
        ~hint:
          "tensor fill factories should carry at least the first dimension by \
           the time they reach C emission"
        "malformed tensor fill factory call"
  | (TensorRawScalarStorage _ | TensorPackedStorage _), _ :: _ -> (
      let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
      let dim_bindings =
        dims
        |> List.mapi (render_fill_dim_bind ~emit_expr ctx temp_seed)
        |> String.concat " "
      in
      let dim_tmps =
        List.mapi (fun i _ -> render_fill_dim_name temp_seed i) dims
      in
      let total_expr = render_fill_total_expr dim_tmps in
      let total_tmp = render_fill_total_name temp_seed in
      let first_dim = render_fill_dim_name temp_seed 0 in
      let value_arg =
        render_arg ~emit_expr ctx (fill_inline_struct_value_source value)
      in
      let alloc_expr =
        render_fill_alloc_call layout ~first_dim ~total_dim:total_tmp loc
      in
      match layout.tsl_slots with
      | TensorRawScalarStorage raw_kind ->
          let value_c_type =
            (Core_layout_type.tensor_raw_scalar_abi raw_kind).tras_c_type
          in
          emit_template ctx "tensor_fill_raw_scalar"
            [
              dim_bindings;
              total_expr;
              value_c_type;
              value_arg;
              alloc_expr;
              temp_seed;
            ]
      | TensorPackedStorage _ ->
          emit_template ctx "tensor_fill_packed"
            [ dim_bindings; total_expr; value_arg; alloc_expr; temp_seed ]
      | TensorInlineStructStorage _ | TensorWordStorage | TensorBoxedStorage ->
          Core_error.errorf Core_error.Emit loc
            ~hint:
              "Only raw numeric and packed tensor fill factories are emitted \
               by this path; boxed and inline-struct tensors use their \
               dedicated ownership-aware emitters."
            "unsupported tensor fill storage layout: %s"
            (tensor_storage_slot_layout_str layout.tsl_slots))
  | (TensorInlineStructStorage _ | TensorWordStorage | TensorBoxedStorage), _ ->
      Core_error.errorf Core_error.Emit loc
        ~hint:
          "Only raw numeric and packed tensor fill factories are emitted by \
           this path; boxed and inline-struct tensors use their dedicated \
           ownership-aware emitters."
        "unsupported tensor fill storage layout: %s"
        (tensor_storage_slot_layout_str layout.tsl_slots)

let emit_alloc ~emit_expr (ctx : Core_emit_context.t) (e : core) size : unit =
  let layout = Core_emit_layout.tensor_storage_layout_of_type ctx e.ty e.loc in
  let requires_release =
    tensor_storage_layout_requires_release_or_error ~phase:Core_error.Emit
      ~loc:e.loc layout
  in
  let release_temp_seed =
    if requires_release then
      Some (string_of_int (Core_emit_context.fresh_temp ctx))
    else None
  in
  let size_arg = render_arg ~emit_expr ctx size in
  let alloc_expr =
    render_alloc_template (alloc_template_of_layout layout) size_arg
  in
  match release_temp_seed with
  | Some temp_seed ->
      emit_template ctx "tensor_alloc_with_release" [ alloc_expr; temp_seed ]
  | None -> Core_emit_context.emit ctx alloc_expr

let emit_raw_view_decl ~emit_expr (ctx : Core_emit_context.t)
    (binding : tensor_raw_view_binding) : unit =
  let pointer_c_type =
    (Core_layout_type.tensor_raw_scalar_abi binding.trv_kind)
      .tras_pointer_c_type
  in
  let source_arg = render_arg ~emit_expr ctx binding.trv_source in
  emit_template ctx "tensor_raw_view_decl"
    [ pointer_c_type; tensor_view_c_name binding.trv_var; source_arg ]

let emit_raw_read ~emit_expr (ctx : Core_emit_context.t)
    (read : tensor_raw_read) : unit =
  let index_arg = render_arg ~emit_expr ctx read.trr_index in
  emit_template ctx "tensor_raw_read"
    [ tensor_view_c_name read.trr_view; index_arg ]

let emit_raw_write_expr ~emit_expr (ctx : Core_emit_context.t)
    (write : tensor_raw_write) : unit =
  let index_arg = render_arg ~emit_expr ctx write.trw_index in
  let value_arg = render_arg ~emit_expr ctx write.trw_value in
  emit_template ctx "tensor_raw_write_expr"
    [ tensor_view_c_name write.trw_view; index_arg; value_arg ]

let emit_raw_write_stmt ~emit_expr (ctx : Core_emit_context.t)
    (write : tensor_raw_write) : unit =
  let index_arg = render_arg ~emit_expr ctx write.trw_index in
  let value_arg = render_arg ~emit_expr ctx write.trw_value in
  emit_template ctx "tensor_raw_write_stmt"
    [ tensor_view_c_name write.trw_view; index_arg; value_arg ]

let emit_storage_check ~emit_expr ctx template tensor =
  let tensor_arg = render_arg ~emit_expr ctx tensor in
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  emit_template ctx
    (storage_check_template_name template)
    [ tensor_arg; temp_seed ]

let emit_word_storage_check ~emit_expr ctx tensor =
  emit_storage_check ~emit_expr ctx WordStorageCheckTemplate tensor

let emit_f64_storage_check ~emit_expr ctx tensor =
  emit_storage_check ~emit_expr ctx F64StorageCheckTemplate tensor

let emit_f32_storage_check ~emit_expr ctx tensor =
  emit_storage_check ~emit_expr ctx F32StorageCheckTemplate tensor

let emit_i64_storage_check ~emit_expr ctx tensor =
  emit_storage_check ~emit_expr ctx I64StorageCheckTemplate tensor

let emit_data_pointer_get_unchecked ~emit_expr ctx tensor index =
  let tensor_arg = render_arg ~emit_expr ctx tensor in
  let index_arg = render_arg ~emit_expr ctx index in
  emit_template ctx "tensor_data_pointer_get_unchecked"
    [ tensor_arg; index_arg ]

let render_inline_struct_get_unchecked ctx ~tensor_arg ~index_arg ~struct_ty =
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  render_template "tensor_inline_struct_get_unchecked"
    [ tensor_arg; index_arg; temp_seed; struct_ty ]

let emit_inline_struct_get_unchecked ~emit_expr ctx tensor index ~struct_ty =
  let tensor_arg = render_arg ~emit_expr ctx tensor in
  let index_arg = render_arg ~emit_expr ctx index in
  Core_emit_context.emit ctx
    (render_inline_struct_get_unchecked ctx ~tensor_arg ~index_arg ~struct_ty)

let emit_inline_struct_get_checked ~emit_expr ctx tensor index ~struct_ty =
  let tensor_arg = render_arg ~emit_expr ctx tensor in
  let index_arg = render_arg ~emit_expr ctx index in
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  emit_template ctx "tensor_inline_struct_get_checked"
    [ tensor_arg; index_arg; temp_seed; struct_ty ]

let emit_inline_struct_matrix_get_checked ~emit_expr ctx tensor row col
    ~struct_ty =
  let tensor_arg = render_arg ~emit_expr ctx tensor in
  let row_arg = render_arg ~emit_expr ctx row in
  let col_arg = render_arg ~emit_expr ctx col in
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  emit_template ctx "tensor_inline_struct_matrix_get_checked"
    [ tensor_arg; row_arg; col_arg; temp_seed; struct_ty ]

let emit_stack_option_vector_get ~emit_expr ctx
    (abi : Core_layout_type.generated_stack_option_get_abi) tensor index =
  let tensor_arg = render_arg ~emit_expr ctx tensor in
  let index_arg = render_arg ~emit_expr ctx index in
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  match abi.gsog_payload_storage with
  | Core_layout_type.GeneratedStackOptionValueRecord payload_c_type ->
      emit_template ctx "tensor_stack_option_vector_get_value_record"
        [
          tensor_arg;
          index_arg;
          temp_seed;
          abi.gsog_option_c_type;
          payload_c_type;
          abi.gsog_none_value;
        ]
  | Core_layout_type.GeneratedStackOptionLong ->
      emit_template ctx "tensor_stack_option_vector_get_long"
        [
          tensor_arg;
          index_arg;
          temp_seed;
          abi.gsog_option_c_type;
          abi.gsog_none_value;
        ]
  | Core_layout_type.GeneratedStackOptionInt128 ->
      emit_template ctx "tensor_stack_option_vector_get_int128"
        [
          tensor_arg;
          index_arg;
          temp_seed;
          abi.gsog_option_c_type;
          abi.gsog_none_value;
        ]
  | Core_layout_type.GeneratedStackOptionUInt128 ->
      emit_template ctx "tensor_stack_option_vector_get_uint128"
        [
          tensor_arg;
          index_arg;
          temp_seed;
          abi.gsog_option_c_type;
          abi.gsog_none_value;
        ]

let emit_stack_option_matrix_get ~emit_expr ctx
    (abi : Core_layout_type.generated_stack_option_get_abi) tensor row col =
  let tensor_arg = render_arg ~emit_expr ctx tensor in
  let row_arg = render_arg ~emit_expr ctx row in
  let col_arg = render_arg ~emit_expr ctx col in
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  match abi.gsog_payload_storage with
  | Core_layout_type.GeneratedStackOptionValueRecord payload_c_type ->
      emit_template ctx "tensor_stack_option_matrix_get_value_record"
        [
          tensor_arg;
          row_arg;
          col_arg;
          temp_seed;
          abi.gsog_option_c_type;
          payload_c_type;
          abi.gsog_none_value;
        ]
  | Core_layout_type.GeneratedStackOptionLong ->
      emit_template ctx "tensor_stack_option_matrix_get_long"
        [
          tensor_arg;
          row_arg;
          col_arg;
          temp_seed;
          abi.gsog_option_c_type;
          abi.gsog_none_value;
        ]
  | Core_layout_type.GeneratedStackOptionInt128 ->
      emit_template ctx "tensor_stack_option_matrix_get_int128"
        [
          tensor_arg;
          row_arg;
          col_arg;
          temp_seed;
          abi.gsog_option_c_type;
          abi.gsog_none_value;
        ]
  | Core_layout_type.GeneratedStackOptionUInt128 ->
      emit_template ctx "tensor_stack_option_matrix_get_uint128"
        [
          tensor_arg;
          row_arg;
          col_arg;
          temp_seed;
          abi.gsog_option_c_type;
          abi.gsog_none_value;
        ]

let emit_inline_struct_element_decl ctx ~var_c ~tensor_c ~index_c ~struct_ty =
  let value =
    render_inline_struct_get_unchecked ctx ~tensor_arg:tensor_c
      ~index_arg:index_c ~struct_ty
  in
  Core_emit_context.emit_line ctx
    (Printf.sprintf "%s %s = %s;" struct_ty var_c value)

let emit_get_unchecked ~emit_expr (ctx : Core_emit_context.t) result tensor
    index =
  match Core_emit_layout.tensor_element_storage ctx result.ty with
  | Core_layout_type.TensorElementInlineStruct c_ty ->
      emit_inline_struct_get_unchecked ~emit_expr ctx tensor index
        ~struct_ty:c_ty
  | Core_layout_type.TensorElementRawScalar _
  | Core_layout_type.TensorElementPackedBits _
  | Core_layout_type.TensorElementBoxed ->
      emit_data_pointer_get_unchecked ~emit_expr ctx tensor index

let emit_raw_scalar_get_unchecked ~emit_expr ctx template tensor index =
  let tensor_arg = render_arg ~emit_expr ctx tensor in
  let index_arg = render_arg ~emit_expr ctx index in
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  emit_template ctx
    (raw_scalar_get_template_name template)
    [ tensor_arg; index_arg; temp_seed ]

let emit_f64_raw_get_unchecked ~emit_expr ctx tensor index =
  emit_raw_scalar_get_unchecked ~emit_expr ctx F64RawGetTemplate tensor index

let emit_f32_raw_get_unchecked ~emit_expr ctx tensor index =
  emit_raw_scalar_get_unchecked ~emit_expr ctx F32RawGetTemplate tensor index
