(** Blorp-owned prepared backend facade templates.

    The template manifest is generated by
    [compiler/blorp/codegen_prepared_backend_renderer.brp]. OCaml still owns
    Core traversal, type/layout analysis, and child expression emission; Blorp
    owns runtime constructor call shapes and release-policy expansion for this
    backend facade slice. *)

open Core

let manifest =
  Core_emit_blorp_template.create ~label:"codegen prepared backend"
    Core_emit_blorp_prepared_backend_templates.tsv

let render_arg = Core_emit_blorp_template.render_arg
let render_template = Core_emit_blorp_template.render_exn manifest

type elem_release_arg = NoElemRelease | ElemReleaseFn
type key_release_policy = KeepKey | ReleaseKey

type dict_constructor_call =
  | DictCtorGeneric
  | DictCtorString
  | DictCtorFloat
  | DictCtorCustom of {
      hash_fn : string;
      equals_fn : string;
      key_release : elem_release_arg;
    }

type dict_capacity_constructor_call =
  | DictWithCapacityGeneric of core
  | DictWithCapacityString of core
  | DictWithCapacityFloat of core
  | DictWithCapacityCustom of {
      capacity : core;
      hash_fn : string;
      equals_fn : string;
      key_release : elem_release_arg;
    }

type set_constructor_call =
  | SetCtorGeneric
  | SetCtorString
  | SetCtorFloat
  | SetCtorCustom of {
      hash_fn : string;
      equals_fn : string;
      elem_release : elem_release_arg;
    }

type channel_retaining_send_runtime =
  | ChannelSendRuntime
  | ChannelTrySendRuntime
  | ChannelTrySendStatusRuntime

type channel_retaining_send_timeout_runtime =
  | ChannelSendTimeoutRuntime
  | ChannelSendTimeoutStatusRuntime

type channel_retaining_send =
  | ChannelRetainingSendNoTimeout of {
      runtime : channel_retaining_send_runtime;
      result_type : string;
      channel : core;
      value : core;
    }
  | ChannelRetainingSendWithTimeout of {
      runtime : channel_retaining_send_timeout_runtime;
      result_type : string;
      channel : core;
      value : core;
      timeout : core;
    }

type channel_send_attempt_constructors = {
  accepted : string;
  would_block : string;
  sealed : string;
  timed_out : string;
}

type channel_send_attempt_value =
  | ChannelSendAttemptDirectValue of core
  | ChannelSendAttemptRetainedValue of core

type channel_send_attempt =
  | ChannelTrySendAttempt of {
      result_type : string;
      channel : core;
      value : channel_send_attempt_value;
      constructors : channel_send_attempt_constructors;
    }
  | ChannelSendTimeoutAttempt of {
      result_type : string;
      channel : core;
      value : channel_send_attempt_value;
      timeout : core;
      constructors : channel_send_attempt_constructors;
    }

type channel_recv_value_release_policy = KeepRecvValue | ReleaseRecvValue

type channel_recv_attempt_constructors = {
  value : string;
  sealed : string;
  empty : string;
}

type channel_recv_attempt =
  | ChannelTryRecvAttempt of {
      result_type : string;
      channel : core;
      release_policy : channel_recv_value_release_policy;
      value_constructor_takes_release_mask : bool;
      constructors : channel_recv_attempt_constructors;
    }
  | ChannelRecvTimeoutAttempt of {
      result_type : string;
      channel : core;
      timeout : core;
      release_policy : channel_recv_value_release_policy;
      value_constructor_takes_release_mask : bool;
      constructors : channel_recv_attempt_constructors;
    }

type stack_option_constructor =
  | StackOptionSomeValue of { option_type : string; value : core }
  | StackOptionSomeVoidStatement of { option_type : string; statement : core }
  | StackOptionNone of { option_type : string; none_value : string }
  | StackOptionTaggedValue of { option_type : string; tag : int; value : core }
  | StackOptionTaggedVoidStatement of {
      option_type : string;
      tag : int;
      statement : core;
    }
  | StackOptionTaggedNone of {
      option_type : string;
      tag : int;
      none_value : string;
    }

type stack_result_payload_release_policy =
  | KeepResultPayload
  | ReleaseResultPayload

type stack_result_constructor =
  | StackResultOkPayload of {
      result_type : string;
      payload : core;
      release_policy : stack_result_payload_release_policy;
    }
  | StackResultErrPayload of {
      result_type : string;
      payload : core;
      release_policy : stack_result_payload_release_policy;
    }
  | StackResultTaggedPayload of {
      result_type : string;
      tag : int;
      field : string;
      payload : boxed_storage_value;
      release_mask : int;
    }

let custom_ctor_template_name ~prefix = function
  | NoElemRelease -> prefix ^ "_custom_no_release"
  | ElemReleaseFn -> prefix ^ "_custom_elem_release"

let render_dict_constructor = function
  | DictCtorGeneric -> render_template "backend_dict_ctor_generic" []
  | DictCtorString -> render_template "backend_dict_ctor_string" []
  | DictCtorFloat -> render_template "backend_dict_ctor_float" []
  | DictCtorCustom { hash_fn; equals_fn; key_release } ->
      render_template
        (custom_ctor_template_name ~prefix:"backend_dict_ctor" key_release)
        [ hash_fn; equals_fn ]

let render_set_constructor = function
  | SetCtorGeneric -> render_template "backend_set_ctor_generic" []
  | SetCtorString -> render_template "backend_set_ctor_string" []
  | SetCtorFloat -> render_template "backend_set_ctor_float" []
  | SetCtorCustom { hash_fn; equals_fn; elem_release } ->
      render_template
        (custom_ctor_template_name ~prefix:"backend_set_ctor" elem_release)
        [ hash_fn; equals_fn ]

let render_set_iter_entry_key ~entry =
  render_template "backend_set_iter_entry_key" [ entry ]

let emit_set_iter_source_binding ~emit_expr ctx ~set source =
  let source_arg = render_arg ~emit_expr ctx source in
  Core_emit_context.emit_line ctx
    (render_template "backend_set_iter_source_binding" [ set; source_arg ])

let emit_set_iter_retain ctx ~set =
  Core_emit_context.emit_line ctx
    (render_template "backend_set_iter_retain" [ set ])

let emit_set_iter_loop_open ctx ~entry ~set =
  Core_emit_context.emit_line ctx
    (render_template "backend_set_iter_loop_open" [ entry; set ])

let emit_set_iter_release ctx ~set =
  Core_emit_context.emit_line ctx
    (render_template "backend_set_iter_release" [ set ])

let render_tuple_name temp_seed =
  render_template "backend_tuple_name" [ temp_seed ]

let render_tuple_arg value_arg =
  render_template "backend_tuple_arg" [ value_arg ]

let render_tuple_args ~emit_boxed ctx elems =
  elems
  |> List.map (fun value ->
      render_tuple_arg (render_arg ~emit_expr:emit_boxed ctx value))
  |> String.concat ""

let emit_tuple_construct ctx ~arity ~args =
  Core_emit_context.emit ctx
    (render_template "backend_tuple_construct" [ arity; args ])

let render_tuple_retain_elem ~tuple_tmp ~index =
  render_template "backend_tuple_retain_elem" [ tuple_tmp; string_of_int index ]

let render_tuple_retain_statements ~tuple_tmp ~retain_mask elems =
  elems
  |> List.mapi (fun i _ ->
      if retain_mask land (1 lsl i) <> 0 then
        Some (render_tuple_retain_elem ~tuple_tmp ~index:i)
      else None)
  |> List.filter_map Fun.id |> String.concat " "

let render_tuple_construct_with_rc ~tuple_tmp ~arity ~args ~retain_statements
    ~release_mask =
  render_template "backend_tuple_construct_with_rc"
    [ tuple_tmp; arity; args; retain_statements; string_of_int release_mask ]

let emit_tuple_construct_with_rc ctx ~tuple_tmp ~arity ~args ~retain_statements
    ~release_mask =
  Core_emit_context.emit ctx
    (render_tuple_construct_with_rc ~tuple_tmp ~arity ~args ~retain_statements
       ~release_mask)

let render_tuple_field_element ~tuple_tmp ~field =
  render_template "backend_tuple_field_element" [ tuple_tmp; field ]

let render_tuple_field_element_at ~tuple_tmp ~index =
  render_tuple_field_element ~tuple_tmp ~field:(string_of_int index)

let render_tuple_field_access ~tuple_tmp ~source ~read =
  render_template "backend_tuple_field_access" [ tuple_tmp; source; read ]

let emit_tuple_field_access ~emit_expr ~render_read ctx obj field =
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let tuple_tmp = render_tuple_name temp_seed in
  let source = render_arg ~emit_expr ctx obj in
  let element = render_tuple_field_element ~tuple_tmp ~field in
  let read = render_read element in
  Core_emit_context.emit ctx
    (render_tuple_field_access ~tuple_tmp ~source ~read)

let emit_tuple_construct_value ~emit_boxed ctx tc =
  let arity = string_of_int (List.length tc.tc_elems) in
  let args = render_tuple_args ~emit_boxed ctx tc.tc_elems in
  if tc.tc_release_mask = 0 then emit_tuple_construct ctx ~arity ~args
  else
    let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
    let tuple_tmp = render_tuple_name temp_seed in
    let retain_statements =
      render_tuple_retain_statements ~tuple_tmp ~retain_mask:tc.tc_retain_mask
        tc.tc_elems
    in
    emit_tuple_construct_with_rc ctx ~tuple_tmp ~arity ~args ~retain_statements
      ~release_mask:tc.tc_release_mask

let emit_string_find_byte_from ~emit_expr ctx source byte start =
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let source_arg = render_arg ~emit_expr ctx source in
  let byte_arg = render_arg ~emit_expr ctx byte in
  let start_arg = render_arg ~emit_expr ctx start in
  Core_emit_context.emit ctx
    (render_template "backend_string_find_byte_from"
       [ source_arg; byte_arg; start_arg; temp_seed ])

let emit_string_byte_read ~emit_expr ctx read =
  let source_arg = render_arg ~emit_expr ctx read.sbr_source in
  let index_arg = render_arg ~emit_expr ctx read.sbr_index in
  Core_emit_context.emit ctx
    (render_template "backend_string_byte_read" [ source_arg; index_arg ])

let emit_string_byte_write ~emit_expr ctx write =
  let target_arg = render_arg ~emit_expr ctx write.sbw_target in
  let index_arg = render_arg ~emit_expr ctx write.sbw_index in
  let byte_arg = render_arg ~emit_expr ctx write.sbw_byte in
  Core_emit_context.emit ctx
    (render_template "backend_string_byte_write"
       [ target_arg; index_arg; byte_arg ])

let emit_string_byte_copy_intrinsic ~emit_expr ctx dst dst_pos src src_pos len =
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let dst_arg = render_arg ~emit_expr ctx dst in
  let dst_pos_arg = render_arg ~emit_expr ctx dst_pos in
  let src_arg = render_arg ~emit_expr ctx src in
  let src_pos_arg = render_arg ~emit_expr ctx src_pos in
  let len_arg = render_arg ~emit_expr ctx len in
  Core_emit_context.emit ctx
    (render_template "backend_string_byte_copy"
       [ dst_arg; dst_pos_arg; src_arg; src_pos_arg; len_arg; temp_seed ])

let emit_string_byte_copy ~emit_expr ctx copy =
  emit_string_byte_copy_intrinsic ~emit_expr ctx copy.sbc_dst copy.sbc_dst_pos
    copy.sbc_src copy.sbc_src_pos copy.sbc_len

let emit_string_set_len_intrinsic ~emit_expr ctx target len =
  let target_arg = render_arg ~emit_expr ctx target in
  let len_arg = render_arg ~emit_expr ctx len in
  Core_emit_context.emit ctx
    (render_template "backend_string_set_len" [ target_arg; len_arg ])

let emit_string_set_len ~emit_expr ctx set_len =
  emit_string_set_len_intrinsic ~emit_expr ctx set_len.ssl_target
    set_len.ssl_len

let render_dict_capacity_constructor ~emit_expr ctx = function
  | DictWithCapacityGeneric capacity ->
      render_template "backend_dict_with_capacity_generic"
        [ render_arg ~emit_expr ctx capacity ]
  | DictWithCapacityString capacity ->
      render_template "backend_dict_with_capacity_string"
        [ render_arg ~emit_expr ctx capacity ]
  | DictWithCapacityFloat capacity ->
      render_template "backend_dict_with_capacity_float"
        [ render_arg ~emit_expr ctx capacity ]
  | DictWithCapacityCustom { capacity; hash_fn; equals_fn; key_release } ->
      render_template
        (custom_ctor_template_name ~prefix:"backend_dict_with_capacity"
           key_release)
        [ render_arg ~emit_expr ctx capacity; hash_fn; equals_fn ]

let render_dict_value_release_init temp_seed =
  render_template "backend_dict_value_release_init" [ temp_seed ]

let render_dict_insert temp_seed ~key_arg ~value_arg =
  render_template "backend_dict_insert" [ temp_seed; key_arg; value_arg ]

let emit_dict_iter_source_binding ~emit_expr ctx ~dict source =
  let source_arg = render_arg ~emit_expr ctx source in
  Core_emit_context.emit_line ctx
    (render_template "backend_dict_iter_source_binding" [ dict; source_arg ])

let emit_dict_iter_loop_open ctx ~index ~dict =
  Core_emit_context.emit_line ctx
    (render_template "backend_dict_iter_loop_open" [ index; dict ])

let emit_dict_iter_slot_binding ctx ~slot ~dict ~index =
  Core_emit_context.emit_line ctx
    (render_template "backend_dict_iter_slot_binding" [ slot; dict; index ])

let emit_dict_iter_deleted_slot_guard ctx ~slot =
  Core_emit_context.emit_line ctx
    (render_template "backend_dict_iter_deleted_slot_guard" [ slot ])

let emit_dict_iter_key_binding ctx ~key_c_type ~binding ~dict ~slot =
  Core_emit_context.emit_line ctx
    (render_template "backend_dict_iter_key_binding"
       [ key_c_type; binding; dict; slot ])

let emit_dict_iter_pair_binding ctx ~entry ~dict ~slot =
  Core_emit_context.emit_line ctx
    (render_template "backend_dict_iter_pair_binding" [ entry; dict; slot ])

let emit_dict_construct_result ctx ~ctor_arg ~value_needs_release =
  if value_needs_release then
    let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
    let release_init = render_dict_value_release_init temp_seed in
    Core_emit_context.emit ctx
      (render_template "backend_dict_construct_with_body"
         [ ctor_arg; temp_seed; release_init; "" ])
  else
    Core_emit_context.emit ctx
      (render_template "backend_dict_construct_empty" [ ctor_arg ])

let emit_dict_construct ~emit_key ~emit_value ctx ~ctor_arg ~value_needs_release
    ~force_wrapper entries =
  if entries = [] && (not value_needs_release) && not force_wrapper then
    Core_emit_context.emit ctx
      (render_template "backend_dict_construct_empty" [ ctor_arg ])
  else
    let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
    let release_init =
      if value_needs_release then render_dict_value_release_init temp_seed
      else ""
    in
    let insert_statements =
      entries
      |> List.map (fun (key, value) ->
          let key_arg = render_arg ~emit_expr:emit_key ctx key in
          let value_arg = render_arg ~emit_expr:emit_value ctx value in
          render_dict_insert temp_seed ~key_arg ~value_arg)
      |> String.concat ""
    in
    Core_emit_context.emit ctx
      (render_template "backend_dict_construct_with_body"
         [ ctor_arg; temp_seed; release_init; insert_statements ])

let dict_stack_option_template_name payload_storage key_release_policy =
  match (payload_storage, key_release_policy) with
  | Core_layout_type.GeneratedStackOptionValueRecord _, KeepKey ->
      "backend_dict_stack_option_get_value_record"
  | Core_layout_type.GeneratedStackOptionValueRecord _, ReleaseKey ->
      "backend_dict_stack_option_get_value_record_release_key"
  | Core_layout_type.GeneratedStackOptionLong, KeepKey ->
      "backend_dict_stack_option_get_long"
  | Core_layout_type.GeneratedStackOptionLong, ReleaseKey ->
      "backend_dict_stack_option_get_long_release_key"
  | Core_layout_type.GeneratedStackOptionInt128, KeepKey ->
      "backend_dict_stack_option_get_int128"
  | Core_layout_type.GeneratedStackOptionInt128, ReleaseKey ->
      "backend_dict_stack_option_get_int128_release_key"
  | Core_layout_type.GeneratedStackOptionUInt128, KeepKey ->
      "backend_dict_stack_option_get_uint128"
  | Core_layout_type.GeneratedStackOptionUInt128, ReleaseKey ->
      "backend_dict_stack_option_get_uint128_release_key"

let emit_dict_stack_option_get ~emit_expr ~emit_boxed ctx
    (abi : Core_layout_type.generated_stack_option_get_abi) dict key
    ~key_release_policy =
  let dict_arg = render_arg ~emit_expr ctx dict in
  let key_arg = render_arg ~emit_expr:emit_boxed ctx key in
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let template_name =
    dict_stack_option_template_name abi.gsog_payload_storage key_release_policy
  in
  match abi.gsog_payload_storage with
  | Core_layout_type.GeneratedStackOptionValueRecord payload_c_type ->
      Core_emit_context.emit ctx
        (render_template template_name
           [
             dict_arg;
             key_arg;
             temp_seed;
             abi.gsog_option_c_type;
             payload_c_type;
             abi.gsog_none_value;
           ])
  | Core_layout_type.GeneratedStackOptionLong
  | Core_layout_type.GeneratedStackOptionInt128
  | Core_layout_type.GeneratedStackOptionUInt128 ->
      Core_emit_context.emit ctx
        (render_template template_name
           [
             dict_arg;
             key_arg;
             temp_seed;
             abi.gsog_option_c_type;
             abi.gsog_none_value;
           ])

let render_channel_with_elem_release ~emit_expr ctx capacity =
  let temp_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let capacity_arg = render_arg ~emit_expr ctx capacity in
  render_template "backend_channel_with_elem_release"
    [ capacity_arg; temp_seed ]

let channel_retaining_send_temp_seeds ctx =
  let value_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let cleanup_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let result_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  (value_seed, cleanup_seed, result_seed)

let channel_retaining_send_template_name = function
  | ChannelSendRuntime -> "backend_channel_send_retaining"
  | ChannelTrySendRuntime -> "backend_channel_try_send_retaining"
  | ChannelTrySendStatusRuntime -> "backend_channel_try_send_status_retaining"

let channel_retaining_send_timeout_template_name = function
  | ChannelSendTimeoutRuntime -> "backend_channel_send_timeout_retaining"
  | ChannelSendTimeoutStatusRuntime ->
      "backend_channel_send_timeout_status_retaining"

let render_channel_retaining_send ~emit_expr ctx = function
  | ChannelRetainingSendNoTimeout { runtime; result_type; channel; value } ->
      let value_seed, cleanup_seed, result_seed =
        channel_retaining_send_temp_seeds ctx
      in
      let value_arg = render_arg ~emit_expr ctx value in
      let channel_arg = render_arg ~emit_expr ctx channel in
      render_template
        (channel_retaining_send_template_name runtime)
        [
          result_type;
          channel_arg;
          value_arg;
          value_seed;
          cleanup_seed;
          result_seed;
        ]
  | ChannelRetainingSendWithTimeout
      { runtime; result_type; channel; value; timeout } ->
      let value_seed, cleanup_seed, result_seed =
        channel_retaining_send_temp_seeds ctx
      in
      let value_arg = render_arg ~emit_expr ctx value in
      let channel_arg = render_arg ~emit_expr ctx channel in
      let timeout_arg = render_arg ~emit_expr ctx timeout in
      render_template
        (channel_retaining_send_timeout_template_name runtime)
        [
          result_type;
          channel_arg;
          value_arg;
          timeout_arg;
          value_seed;
          cleanup_seed;
          result_seed;
        ]

let channel_send_attempt_temp_seeds ctx =
  let status_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let result_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  (status_seed, result_seed)

let channel_send_attempt_retained_value_temp_seeds ctx =
  let value_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let cleanup_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  (value_seed, cleanup_seed)

let channel_send_attempt_constructor_args constructors =
  [
    constructors.accepted;
    constructors.would_block;
    constructors.sealed;
    constructors.timed_out;
  ]

let render_channel_try_send_attempt ~emit_expr ctx ~result_type ~channel ~value
    ~constructors =
  let status_seed, result_seed = channel_send_attempt_temp_seeds ctx in
  match value with
  | ChannelSendAttemptDirectValue value ->
      let channel_arg = render_arg ~emit_expr ctx channel in
      let value_arg = render_arg ~emit_expr ctx value in
      render_template "backend_channel_try_send_attempt"
        ([ result_type; channel_arg; value_arg; status_seed; result_seed ]
        @ channel_send_attempt_constructor_args constructors)
  | ChannelSendAttemptRetainedValue value ->
      let value_seed, cleanup_seed =
        channel_send_attempt_retained_value_temp_seeds ctx
      in
      let value_arg = render_arg ~emit_expr ctx value in
      let channel_arg = render_arg ~emit_expr ctx channel in
      render_template "backend_channel_try_send_attempt_retained_value"
        ([
           result_type;
           channel_arg;
           value_arg;
           status_seed;
           result_seed;
           value_seed;
           cleanup_seed;
         ]
        @ channel_send_attempt_constructor_args constructors)

let render_channel_send_timeout_attempt ~emit_expr ctx ~result_type ~channel
    ~value ~timeout ~constructors =
  let status_seed, result_seed = channel_send_attempt_temp_seeds ctx in
  match value with
  | ChannelSendAttemptDirectValue value ->
      let channel_arg = render_arg ~emit_expr ctx channel in
      let value_arg = render_arg ~emit_expr ctx value in
      let timeout_arg = render_arg ~emit_expr ctx timeout in
      render_template "backend_channel_send_timeout_attempt"
        ([
           result_type;
           channel_arg;
           value_arg;
           timeout_arg;
           status_seed;
           result_seed;
         ]
        @ channel_send_attempt_constructor_args constructors)
  | ChannelSendAttemptRetainedValue value ->
      let value_seed, cleanup_seed =
        channel_send_attempt_retained_value_temp_seeds ctx
      in
      let value_arg = render_arg ~emit_expr ctx value in
      let channel_arg = render_arg ~emit_expr ctx channel in
      let timeout_arg = render_arg ~emit_expr ctx timeout in
      render_template "backend_channel_send_timeout_attempt_retained_value"
        ([
           result_type;
           channel_arg;
           value_arg;
           timeout_arg;
           status_seed;
           result_seed;
           value_seed;
           cleanup_seed;
         ]
        @ channel_send_attempt_constructor_args constructors)

let render_channel_send_attempt ~emit_expr ctx = function
  | ChannelTrySendAttempt { result_type; channel; value; constructors } ->
      render_channel_try_send_attempt ~emit_expr ctx ~result_type ~channel
        ~value ~constructors
  | ChannelSendTimeoutAttempt
      { result_type; channel; value; timeout; constructors } ->
      render_channel_send_timeout_attempt ~emit_expr ctx ~result_type ~channel
        ~value ~timeout ~constructors

let channel_recv_attempt_temp_seeds ctx =
  let value_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let status_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  let result_seed = string_of_int (Core_emit_context.fresh_temp ctx) in
  (value_seed, status_seed, result_seed)

let channel_recv_value_release_mask = function
  | KeepRecvValue -> "0"
  | ReleaseRecvValue -> "1"

let channel_recv_attempt_constructor_args constructors =
  [ constructors.value; constructors.sealed; constructors.empty ]

let render_channel_try_recv_attempt ~emit_expr ctx ~result_type ~channel
    ~release_policy ~value_constructor_takes_release_mask ~constructors =
  let value_seed, status_seed, result_seed =
    channel_recv_attempt_temp_seeds ctx
  in
  let channel_arg = render_arg ~emit_expr ctx channel in
  if value_constructor_takes_release_mask then
    render_template "backend_channel_try_recv_attempt"
      ([
         result_type;
         channel_arg;
         value_seed;
         status_seed;
         result_seed;
         channel_recv_value_release_mask release_policy;
       ]
      @ channel_recv_attempt_constructor_args constructors)
  else
    render_template "backend_channel_try_recv_attempt_no_release_mask"
      ([ result_type; channel_arg; value_seed; status_seed; result_seed ]
      @ channel_recv_attempt_constructor_args constructors)

let render_channel_recv_timeout_attempt ~emit_expr ctx ~result_type ~channel
    ~timeout ~release_policy ~value_constructor_takes_release_mask ~constructors
    =
  let value_seed, status_seed, result_seed =
    channel_recv_attempt_temp_seeds ctx
  in
  let channel_arg = render_arg ~emit_expr ctx channel in
  let timeout_arg = render_arg ~emit_expr ctx timeout in
  if value_constructor_takes_release_mask then
    render_template "backend_channel_recv_timeout_attempt"
      ([
         result_type;
         channel_arg;
         timeout_arg;
         value_seed;
         status_seed;
         result_seed;
         channel_recv_value_release_mask release_policy;
       ]
      @ channel_recv_attempt_constructor_args constructors)
  else
    render_template "backend_channel_recv_timeout_attempt_no_release_mask"
      ([
         result_type;
         channel_arg;
         timeout_arg;
         value_seed;
         status_seed;
         result_seed;
       ]
      @ channel_recv_attempt_constructor_args constructors)

let render_channel_recv_attempt ~emit_expr ctx = function
  | ChannelTryRecvAttempt
      {
        result_type;
        channel;
        release_policy;
        value_constructor_takes_release_mask;
        constructors;
      } ->
      render_channel_try_recv_attempt ~emit_expr ctx ~result_type ~channel
        ~release_policy ~value_constructor_takes_release_mask ~constructors
  | ChannelRecvTimeoutAttempt
      {
        result_type;
        channel;
        timeout;
        release_policy;
        value_constructor_takes_release_mask;
        constructors;
      } ->
      render_channel_recv_timeout_attempt ~emit_expr ctx ~result_type ~channel
        ~timeout ~release_policy ~value_constructor_takes_release_mask
        ~constructors

let render_stack_option_constructor ~emit_expr ~emit_stmt ctx = function
  | StackOptionSomeValue { option_type; value } ->
      render_template "backend_stack_option_some_value"
        [ option_type; render_arg ~emit_expr ctx value ]
  | StackOptionSomeVoidStatement { option_type; statement } ->
      render_template "backend_stack_option_some_void_statement"
        [ option_type; render_arg ~emit_expr:emit_stmt ctx statement ]
  | StackOptionNone { option_type; none_value } ->
      render_template "backend_stack_option_none" [ option_type; none_value ]
  | StackOptionTaggedValue { option_type; tag; value } ->
      render_template "backend_stack_option_tagged_value"
        [ option_type; string_of_int tag; render_arg ~emit_expr ctx value ]
  | StackOptionTaggedVoidStatement { option_type; tag; statement } ->
      render_template "backend_stack_option_tagged_void_statement"
        [
          option_type;
          string_of_int tag;
          render_arg ~emit_expr:emit_stmt ctx statement;
        ]
  | StackOptionTaggedNone { option_type; tag; none_value } ->
      render_template "backend_stack_option_tagged_none"
        [ option_type; string_of_int tag; none_value ]

let stack_result_payload_release_mask = function
  | KeepResultPayload -> "0"
  | ReleaseResultPayload -> "1"

let render_stack_result_payload_constructor ~emit_boxed ctx template_name
    ~result_type ~payload ~release_policy =
  render_template template_name
    [
      result_type;
      render_arg ~emit_expr:emit_boxed ctx payload;
      stack_result_payload_release_mask release_policy;
    ]

let render_stack_result_constructor ~emit_boxed ~emit_boxed_storage ctx =
  function
  | StackResultOkPayload { result_type; payload; release_policy } ->
      render_stack_result_payload_constructor ~emit_boxed ctx
        "backend_stack_result_ok" ~result_type ~payload ~release_policy
  | StackResultErrPayload { result_type; payload; release_policy } ->
      render_stack_result_payload_constructor ~emit_boxed ctx
        "backend_stack_result_err" ~result_type ~payload ~release_policy
  | StackResultTaggedPayload { result_type; tag; field; payload; release_mask }
    ->
      render_template "backend_stack_result_tagged_payload"
        [
          result_type;
          string_of_int tag;
          field;
          render_arg ~emit_expr:emit_boxed_storage ctx payload;
          string_of_int release_mask;
        ]
