(** Blorp-owned simple intrinsic templates for the C backend.

    The template manifest is generated by
    [tools/compiler/codegen_intrinsic_renderer.brp]. OCaml still owns Core
    traversal and subexpression emission; this module owns only the generic
    placeholder substitution needed to use those Blorp-authored templates in
    the production emitter. *)

type template = { name : string; arity : int; body : string }

let manifest_tsv = Embedded_codegen_intrinsic_templates.tsv

let strip_trailing_cr line =
  let len = String.length line in
  if len > 0 && line.[len - 1] = '\r' then String.sub line 0 (len - 1) else line

let parse_manifest_line line_no line =
  let line = strip_trailing_cr line in
  if String.trim line = "" || line.[0] = '#' then None
  else
    match String.split_on_char '\t' line with
    | [ name; arity_text; body ] -> (
        match int_of_string_opt arity_text with
        | Some arity when arity >= 0 -> Some { name; arity; body }
        | _ ->
            invalid_arg
              (Printf.sprintf
                 "invalid codegen intrinsic template arity on line %d: %S"
                 line_no arity_text))
    | fields ->
        invalid_arg
          (Printf.sprintf
             "invalid codegen intrinsic template line %d: expected 3 TSV \
              fields, got %d"
             line_no (List.length fields))

let templates =
  lazy
    (manifest_tsv |> String.split_on_char '\n'
    |> List.mapi (fun i line -> parse_manifest_line (i + 1) line)
    |> List.filter_map Fun.id)

let table =
  lazy
    (let tbl = Hashtbl.create 64 in
     List.iter
       (fun template ->
         if Hashtbl.mem tbl template.name then
           invalid_arg
             (Printf.sprintf "duplicate codegen intrinsic template for %S"
                template.name);
         Hashtbl.add tbl template.name template)
       (Lazy.force templates);
     tbl)

let names () =
  Lazy.force templates
  |> List.map (fun template -> template.name)
  |> List.sort_uniq String.compare

let find name = Hashtbl.find_opt (Lazy.force table) name

let render_arg ~emit_expr (ctx : Core_emit_context.t) arg =
  let original_output = ctx.output in
  let arg_output = Buffer.create 128 in
  ctx.output <- arg_output;
  Fun.protect
    ~finally:(fun () -> ctx.output <- original_output)
    (fun () ->
      emit_expr ctx arg;
      Buffer.contents arg_output)

let substitute template args =
  if List.length args <> template.arity then
    invalid_arg
      (Printf.sprintf "template %S expected %d args, got %d" template.name
         template.arity (List.length args));
  let rendered_args = Array.of_list args in
  let body = template.body in
  let len = String.length body in
  let buf = Buffer.create (len + 32) in
  let is_digit c = c >= '0' && c <= '9' in
  let rec go i =
    if i >= len then ()
    else if
      body.[i] = '@'
      && i + 2 < len
      && is_digit body.[i + 1]
      && body.[i + 2] = '@'
    then begin
      let arg_index = Char.code body.[i + 1] - Char.code '0' in
      if arg_index >= Array.length rendered_args then
        invalid_arg
          (Printf.sprintf
             "template %S references arg %d but only %d args are available"
             template.name arg_index
             (Array.length rendered_args));
      Buffer.add_string buf rendered_args.(arg_index);
      go (i + 3)
    end
    else begin
      Buffer.add_char buf body.[i];
      go (i + 1)
    end
  in
  go 0;
  Buffer.contents buf

let emit ~emit_expr (ctx : Core_emit_context.t) name args =
  match find name with
  | None -> false
  | Some template ->
      if List.length args <> template.arity then false
      else begin
        let rendered_args = List.map (render_arg ~emit_expr ctx) args in
        Core_emit_context.emit ctx (substitute template rendered_args);
        true
      end
