(** Blorp-owned prepared set templates for the C backend.

    The template manifest is generated by
    [compiler/blorp/codegen_prepared_set_renderer.brp]. OCaml still owns Core
    traversal, child expression emission, type-directed element unboxing, and
    fresh temp seeds; Blorp owns the C snippet shape for prepared set templates.
*)

open Core_emit_context

let manifest =
  Core_emit_blorp_template.create ~label:"codegen prepared set"
    Core_emit_blorp_prepared_set_templates.tsv

let render_arg = Core_emit_blorp_template.render_arg
let render_template = Core_emit_blorp_template.render_exn manifest

let render_iter_source_binding ~set ~source =
  render_template "set_iter_source_binding" [ set; source ]

let render_iter_retain ~set = render_template "set_iter_retain" [ set ]

let render_iter_loop_open ~entry ~set =
  render_template "set_iter_loop_open" [ entry; set ]

let render_iter_entry_key ~entry =
  render_template "set_iter_entry_key" [ entry ]

let render_iter_release ~set = render_template "set_iter_release" [ set ]

let emit_iter_source_binding ~emit_expr ctx ~set source =
  let source_arg = render_arg ~emit_expr ctx source in
  emit_line ctx (render_iter_source_binding ~set ~source:source_arg)

let emit_iter_retain ctx ~set = emit_line ctx (render_iter_retain ~set)

let emit_iter_loop_open ctx ~entry ~set =
  emit_line ctx (render_iter_loop_open ~entry ~set)

let emit_iter_release ctx ~set = emit_line ctx (render_iter_release ~set)
