(** Blorp-owned prepared tensor templates for the C backend.

    The template manifest is generated by
    [compiler/blorp/codegen_prepared_tensor_renderer.brp]. OCaml still owns
    Core traversal, child expression emission, ABI strings, and variable-name
    escaping; this module owns only placeholder substitution for Blorp-authored
    prepared tensor Core node templates. *)

open Core

let manifest =
  Core_emit_blorp_template.create ~label:"codegen prepared tensor"
    Core_emit_blorp_prepared_tensor_templates.tsv

let render_arg = Core_emit_blorp_template.render_arg
let emit_template = Core_emit_blorp_template.emit manifest
let tensor_view_c_name v = Codegen_types.escape_c_ident (Var.to_c_name v)

let emit_raw_view_decl ~emit_expr (ctx : Core_emit_context.t)
    (binding : tensor_raw_view_binding) : unit =
  let pointer_c_type =
    (Core_layout_type.tensor_raw_scalar_abi binding.trv_kind)
      .tras_pointer_c_type
  in
  let source_arg = render_arg ~emit_expr ctx binding.trv_source in
  emit_template ctx "tensor_raw_view_decl"
    [ pointer_c_type; tensor_view_c_name binding.trv_var; source_arg ]

let emit_raw_read ~emit_expr (ctx : Core_emit_context.t)
    (read : tensor_raw_read) : unit =
  let index_arg = render_arg ~emit_expr ctx read.trr_index in
  emit_template ctx "tensor_raw_read"
    [ tensor_view_c_name read.trr_view; index_arg ]

let emit_raw_write_expr ~emit_expr (ctx : Core_emit_context.t)
    (write : tensor_raw_write) : unit =
  let index_arg = render_arg ~emit_expr ctx write.trw_index in
  let value_arg = render_arg ~emit_expr ctx write.trw_value in
  emit_template ctx "tensor_raw_write_expr"
    [ tensor_view_c_name write.trw_view; index_arg; value_arg ]

let emit_raw_write_stmt ~emit_expr (ctx : Core_emit_context.t)
    (write : tensor_raw_write) : unit =
  let index_arg = render_arg ~emit_expr ctx write.trw_index in
  let value_arg = render_arg ~emit_expr ctx write.trw_value in
  emit_template ctx "tensor_raw_write_stmt"
    [ tensor_view_c_name write.trw_view; index_arg; value_arg ]
