(** Blorp-owned simple intrinsic templates for the C backend.

    The template manifest is generated by
    [compiler/blorp/codegen_intrinsic_renderer.brp]. OCaml still owns Core
    traversal and subexpression emission; this module owns only the generic
    placeholder substitution needed to use those Blorp-authored templates in
    the production emitter. *)

let manifest =
  Core_emit_blorp_template.create ~initial_size:64 ~label:"codegen intrinsic"
    Core_emit_blorp_intrinsic_templates.tsv

let names () = Core_emit_blorp_template.names manifest

let emit ~emit_expr (ctx : Core_emit_context.t) name args =
  match Core_emit_blorp_template.find manifest name with
  | Some template when List.length args = template.arity ->
      let rendered_args =
        Core_emit_blorp_template.render_args ~emit_expr ctx args
      in
      Core_emit_blorp_template.emit manifest ctx name rendered_args;
      true
  | Some _ | None -> false
