(** Blorp-owned prepared list templates for the C backend.

    The template manifest is generated by
    [compiler/blorp/codegen_prepared_list_renderer.brp]. OCaml still owns Core
    traversal, child expression emission, layout metadata, and fresh temp
    allocation; this module owns only placeholder substitution for
    Blorp-authored prepared list Core node templates. *)

open Core
open Core_emit_context

let manifest =
  Core_emit_blorp_template.create ~label:"codegen prepared list"
    Core_emit_blorp_prepared_list_templates.tsv

let render_arg = Core_emit_blorp_template.render_arg
let emit_template = Core_emit_blorp_template.emit manifest

let emit_runtime_get ~emit_expr ctx ~template_name list index =
  let list_arg = render_arg ~emit_expr ctx list in
  let index_arg = render_arg ~emit_expr ctx index in
  emit_template ctx template_name [ list_arg; index_arg ]

let emit_inline_get ~emit_expr ctx get width =
  let list_tmp = Printf.sprintf "__lg_list_%d" (fresh_temp ctx) in
  let idx_tmp = Printf.sprintf "__lg_idx_%d" (fresh_temp ctx) in
  let bits_tmp = Printf.sprintf "__lg_bits_%d" (fresh_temp ctx) in
  let width_bytes = string_of_int (inline_storage_width_bytes width) in
  let template_name =
    match get.lg_bounds with
    | ListBoundsChecked -> "list_get_inline_checked"
    | ListBoundsProven -> "list_get_inline_proven"
  in
  let list_arg = render_arg ~emit_expr ctx get.lg_list in
  let index_arg = render_arg ~emit_expr ctx get.lg_index in
  emit_template ctx template_name
    [ list_arg; index_arg; list_tmp; idx_tmp; bits_tmp; width_bytes ]

let emit_inline_struct_dynamic_load ctx ~list_tmp ~idx_tmp ~out_tmp ~struct_ty
    ~bounds =
  let raw_tmp = Printf.sprintf "__lg_raw_%d" (fresh_temp ctx) in
  let template_name =
    match bounds with
    | ListBoundsChecked -> "list_inline_struct_load_checked"
    | ListBoundsProven -> "list_inline_struct_load_proven"
  in
  emit_template ctx template_name
    [ list_tmp; idx_tmp; out_tmp; raw_tmp; struct_ty ]

let emit_inline_bits_load ctx ~list_tmp ~idx_tmp ~bits_tmp ~width =
  let width_bytes = string_of_int (inline_storage_width_bytes width) in
  emit_template ctx "list_inline_bits_load"
    [ list_tmp; idx_tmp; bits_tmp; width_bytes ]

let emit_get ~emit_expr (ctx : Core_emit_context.t) (get : list_get) : unit =
  match get.lg_layout.lsl_slots with
  | ListPointerStorage ->
      emit_runtime_get ~emit_expr ctx ~template_name:"list_get_pointer"
        get.lg_list get.lg_index
  | ListInlineStorage width -> emit_inline_get ~emit_expr ctx get width
  | ListInlineStructStorage _ ->
      emit_runtime_get ~emit_expr ctx ~template_name:"list_get_pointer"
        get.lg_list get.lg_index
