(* tools/gen_embed_formatter.ml — Build-time script to embed formatter sources.
   Invoked by make: ocaml compiler/tools/gen_embed_formatter.ml tools/formatter
   Outputs embedded_formatter.ml to stdout. *)

let read_file path =
  let ic = open_in_bin path in
  Fun.protect
    ~finally:(fun () -> close_in ic)
    (fun () ->
      let n = in_channel_length ic in
      really_input_string ic n)

let () =
  let args = Array.to_list Sys.argv |> List.tl in
  let formatter_dir =
    match args with
    | dir :: _ -> dir
    | [] ->
        Printf.eprintf "Usage: gen_embed_formatter.ml <formatter_dir>\n";
        exit 1
  in
  let files = ref [] in
  let rec walk dir prefix =
    let entries = Sys.readdir dir in
    Array.sort String.compare entries;
    Array.iter
      (fun name ->
        let path = Filename.concat dir name in
        if Sys.is_directory path then walk path (prefix ^ name ^ "/")
        else if Filename.check_suffix name ".brp" then
          let embedded_path = "tools/formatter/" ^ prefix ^ name in
          files := (embedded_path, read_file path) :: !files)
      entries
  in
  walk formatter_dir "";
  let files = List.sort (fun (a, _) (b, _) -> String.compare a b) !files in
  let digest_input =
    String.concat "\000"
      (List.concat_map (fun (path, source) -> [ path; source ]) files)
  in
  let digest = Digest.to_hex (Digest.string digest_input) in
  Printf.printf
    "(* Generated by gen_embed_formatter.ml — do not edit *)\n\n\
     [@@@ocamlformat \"disable\"]\n\n";
  Printf.printf "let main_path = %S\n\n" "tools/formatter/formatter.brp";
  Printf.printf "let digest = %S\n\n" digest;
  Printf.printf "let files : (string * string) list = [\n";
  List.iter
    (fun (name, content) -> Printf.printf "  (%S, %S);\n" name content)
    files;
  Printf.printf "]\n\n";
  Printf.printf "let find path = List.assoc_opt path files\n"
