(* tools/gen_embed_std.ml — Build-time script to embed std library sources.
   Invoked by dune: ocaml tools/gen_embed_std.ml <std_dir>
   Outputs embedded_std.ml to stdout. *)

let () =
  let args = Array.to_list Sys.argv |> List.tl in
  let std_dir =
    match args with
    | dir :: _ -> dir
    | [] ->
        Printf.eprintf "Usage: gen_embed_std.ml <std_dir>\n";
        exit 1
  in
  let modules = ref [] in
  let rec walk dir prefix =
    let entries = Sys.readdir dir in
    Array.sort String.compare entries;
    Array.iter
      (fun name ->
        let path = Filename.concat dir name in
        if Sys.is_directory path then walk path (prefix ^ name ^ "/")
        else if Filename.check_suffix name ".brp" then begin
          let mod_name = "std/" ^ prefix ^ Filename.chop_suffix name ".brp" in
          let ic = open_in path in
          let n = in_channel_length ic in
          let content = really_input_string ic n in
          close_in ic;
          modules := (mod_name, content) :: !modules
        end)
      entries
  in
  walk std_dir "";
  let modules = List.sort (fun (a, _) (b, _) -> String.compare a b) !modules in
  Printf.printf "(* Generated by gen_embed_std.ml — do not edit *)\n\n";
  Printf.printf "let modules : (string * string) list = [\n";
  List.iter
    (fun (name, content) -> Printf.printf "  (%S, %S);\n" name content)
    modules;
  Printf.printf "]\n\n";
  Printf.printf "let find name = List.assoc_opt name modules\n"
