(* tools/gen_embed_std.ml — Build-time script to embed std library sources.
   Invoked by dune: ocaml tools/gen_embed_std.ml <std_dir>
   Pass [--blorp] to generate the Blorp compiler's source lookup instead. *)

type output_format = Ocaml | Blorp

let usage () =
  Printf.eprintf "Usage: gen_embed_std.ml [--blorp] <std_dir>\n";
  exit 1

let output_and_directory = function
  | [ std_dir ] -> (Ocaml, std_dir)
  | [ "--blorp"; std_dir ] -> (Blorp, std_dir)
  | _ -> usage ()

let emit_ocaml modules digest =
  Printf.printf "(* Generated by gen_embed_std.ml — do not edit *)\n\n";
  Printf.printf "let digest = %S\n\n" digest;
  Printf.printf "let modules : (string * string) list = [\n";
  List.iter
    (fun (name, content) -> Printf.printf "  (%S, %S);\n" name content)
    modules;
  Printf.printf "]\n\n";
  Printf.printf "let find name = List.assoc_opt name modules\n"

let emit_blorp_source content =
  String.split_on_char '\n' content
  |> List.iter (fun line -> Printf.printf "\t\t\t\t|%s\n" line)

let emit_blorp modules digest =
  Printf.printf "-- Generated by gen_embed_std.ml --blorp; do not edit.\n";
  Printf.printf "embedded_std_digest: String = %S\n\n" digest;
  Printf.printf
    "pure func embedded_std_source(module_name: String) -> Option[String]:\n";
  Printf.printf "\tmatch module_name:\n";
  List.iter
    (fun (name, content) ->
      Printf.printf "\t\t%S:\n" name;
      Printf.printf "\t\t\tsource: String = raw\n";
      emit_blorp_source content;
      Printf.printf "\t\t\tSome(source)\n")
    modules;
  Printf.printf "\t\t_:\n\t\t\tNone\n"

let () =
  let args = Array.to_list Sys.argv |> List.tl in
  let output_format, std_dir = output_and_directory args in
  let modules = ref [] in
  let rec walk dir prefix =
    let entries = Sys.readdir dir in
    Array.sort String.compare entries;
    Array.iter
      (fun name ->
        let path = Filename.concat dir name in
        if Sys.is_directory path then walk path (prefix ^ name ^ "/")
        else if Filename.check_suffix name ".brp" then begin
          let mod_name = "std/" ^ prefix ^ Filename.chop_suffix name ".brp" in
          let ic = open_in path in
          let n = in_channel_length ic in
          let content = really_input_string ic n in
          close_in ic;
          modules := (mod_name, content) :: !modules
        end)
      entries
  in
  walk std_dir "";
  let modules = List.sort (fun (a, _) (b, _) -> String.compare a b) !modules in
  let digest_input =
    String.concat "\000"
      (List.concat_map (fun (name, content) -> [ name; content ]) modules)
  in
  let digest = Digest.to_hex (Digest.string digest_input) in
  match output_format with
  | Ocaml -> emit_ocaml modules digest
  | Blorp -> emit_blorp modules digest
