(* Build-time script that emits compiler provenance metadata.

   The generated module is intentionally small and string-based. Release
   workflows provide these values through BLORP_BUILD_* environment variables;
   local builds fall back to stable "local/unknown" values. *)

let getenv_default name default =
  match Sys.getenv_opt name with Some value -> value | None -> default

let emit_string name value = Printf.printf "let %s = %S\n" name value

let () =
  Printf.printf "(* Generated by gen_build_info.ml — do not edit *)\n\n";
  emit_string "version_override" (getenv_default "BLORP_BUILD_VERSION" "");
  emit_string "commit" (getenv_default "BLORP_BUILD_COMMIT" "unknown");
  emit_string "target" (getenv_default "BLORP_BUILD_TARGET" "unknown");
  emit_string "channel" (getenv_default "BLORP_BUILD_CHANNEL" "local");
  emit_string "dirty" (getenv_default "BLORP_BUILD_DIRTY" "unknown")
