(* Generate the embedded standard-library lookup used by the Blorp compiler. *)

let usage () =
  Printf.eprintf "Usage: gen_embed_std.ml <std_dir>\n";
  exit 1

let input_directory = function
  | [ std_dir ] -> std_dir
  | _ -> usage ()

let emit_blorp_source content =
  String.split_on_char '\n' content
  |> List.iter (fun line -> Printf.printf "\t\t\t\t|%s\n" line)

let emit modules digest =
  Printf.printf "-- Generated by gen_embed_std.ml; do not edit.\n";
  Printf.printf "embedded_std_digest: String = %S\n\n" digest;
  Printf.printf "pure func embedded_std_module_names() -> List[String]:\n";
  Printf.printf "\t[\n";
  List.iter (fun (name, _) -> Printf.printf "\t\t%S,\n" name) modules;
  Printf.printf "\t]\n\n\n";
  Printf.printf
    "pure func embedded_std_source(module_name: String) -> Option[String]:\n";
  Printf.printf "\tmatch module_name:\n";
  List.iter
    (fun (name, content) ->
      Printf.printf "\t\t%S:\n" name;
      Printf.printf "\t\t\tsource: String = raw\n";
      emit_blorp_source content;
      Printf.printf "\t\t\tSome(source)\n")
    modules;
  Printf.printf "\t\t_:\n\t\t\tNone\n"

let () =
  let args = Array.to_list Sys.argv |> List.tl in
  let std_dir = input_directory args in
  let modules = ref [] in
  let rec walk dir prefix =
    let entries = Sys.readdir dir in
    Array.sort String.compare entries;
    Array.iter
      (fun name ->
        let path = Filename.concat dir name in
        if Sys.is_directory path then walk path (prefix ^ name ^ "/")
        else if Filename.check_suffix name ".brp" then begin
          let mod_name = "std/" ^ prefix ^ Filename.chop_suffix name ".brp" in
          let ic = open_in path in
          let n = in_channel_length ic in
          let content = really_input_string ic n in
          close_in ic;
          modules := (mod_name, content) :: !modules
        end)
      entries
  in
  walk std_dir "";
  let modules = List.sort (fun (a, _) (b, _) -> String.compare a b) !modules in
  let digest_input =
    String.concat "\000"
      (List.concat_map (fun (name, content) -> [ name; content ]) modules)
  in
  let digest = Digest.to_hex (Digest.string digest_input) in
  emit modules digest
