(* Build-time script that emits Blorp compiler provenance metadata. *)

let getenv_default name default =
  match Sys.getenv_opt name with Some value -> value | None -> default

let usage () =
  Printf.eprintf "Usage: gen_build_info.ml <version-file>\n";
  exit 1

let version_file =
  match Array.to_list Sys.argv |> List.tl with
  | [ path ] -> path
  | _ -> usage ()

let read_source_version path =
  let channel = open_in_bin path in
  Fun.protect
    ~finally:(fun () -> close_in_noerr channel)
    (fun () ->
      match input_line channel with
      | version when version <> "" ->
          (try
             ignore (input_line channel);
             failwith "version file must contain exactly one line"
           with End_of_file -> version)
      | _ -> failwith "version file must contain a non-empty version")

let emit_string name value = Printf.printf "private %s: String = %S\n\n" name value

let () =
  Printf.printf "-- Generated by gen_build_info.ml; do not edit.\n";
  Printf.printf "import:\n\tembedded_std: embedded_std_digest\n\n\n";
  emit_string "BUILD_SOURCE_VERSION" (read_source_version version_file);
  emit_string "BUILD_VERSION_OVERRIDE" (getenv_default "BLORP_BUILD_VERSION" "");
  emit_string "BUILD_COMMIT" (getenv_default "BLORP_BUILD_COMMIT" "unknown");
  emit_string "BUILD_TARGET" (getenv_default "BLORP_BUILD_TARGET" "unknown");
  emit_string "BUILD_CHANNEL" (getenv_default "BLORP_BUILD_CHANNEL" "local");
  emit_string "BUILD_DIRTY" (getenv_default "BLORP_BUILD_DIRTY" "unknown");
  Printf.printf
    "\npure func compiler_version() -> String:\n\tif BUILD_VERSION_OVERRIDE == \"\":\n\t\tBUILD_SOURCE_VERSION\n\telse:\n\t\tBUILD_VERSION_OVERRIDE\n\n\npure func compiler_version_description() -> String:\n\t\"blorp \" + compiler_version() + \"\\ncommit: \" + BUILD_COMMIT + \"\\ntarget: \" + BUILD_TARGET + \"\\nchannel: \" + BUILD_CHANNEL + \"\\ndirty: \" + BUILD_DIRTY + \"\\nstd: embedded, hash \" + embedded_std_digest\n"
